// FONTS_BASE is loaded from fonts-data.js

// ?? SHARED language-support helper (used on both card & detail page) ??
// Accurate per-font subset data from Google Fonts (statically defined)
const FONT_SUBSETS = {
  'inter':              ['Latin','Latin Ext','Cyrillic','Cyrillic Ext','Greek'],
  'montserrat':         ['Latin','Latin Ext','Cyrillic','Cyrillic Ext','Vietnamese'],
  'open-sans':          ['Latin','Latin Ext','Cyrillic','Cyrillic Ext','Greek','Greek Ext','Hebrew','Vietnamese'],
  'lato':               ['Latin','Latin Ext'],
  'poppins':            ['Latin','Latin Ext','Devanagari'],
  'nunito':             ['Latin','Latin Ext','Cyrillic','Vietnamese'],
  'raleway':            ['Latin','Latin Ext'],
  'oswald':             ['Latin','Latin Ext','Cyrillic','Vietnamese'],
  'roboto':             ['Latin','Latin Ext','Cyrillic','Cyrillic Ext','Greek','Greek Ext','Vietnamese'],
  'dm-sans':            ['Latin','Latin Ext'],
  'outfit':             ['Latin'],
  'figtree':            ['Latin','Latin Ext'],
  'barlow':             ['Latin','Latin Ext','Vietnamese'],
  'playfair-display':   ['Latin','Latin Ext','Cyrillic','Vietnamese'],
  'merriweather':       ['Latin','Latin Ext','Cyrillic','Vietnamese'],
  'lora':               ['Latin','Latin Ext','Cyrillic','Vietnamese'],
  'cormorant-garamond': ['Latin','Latin Ext','Cyrillic','Vietnamese'],
  'eb-garamond':        ['Latin','Latin Ext','Cyrillic','Greek','Vietnamese'],
  'cinzel':             ['Latin','Latin Ext'],
  'spectral':           ['Latin','Latin Ext','Cyrillic','Vietnamese'],
  'pt-serif':           ['Latin','Latin Ext','Cyrillic'],
  'bebas-neue':         ['Latin','Latin Ext'],
  'abril-fatface':      ['Latin','Latin Ext'],
  'syne':               ['Latin','Latin Ext','Greek'],
  'space-grotesk':      ['Latin','Latin Ext'],
  'fredoka':            ['Latin','Latin Ext','Hebrew'],
  'bangers':            ['Latin','Latin Ext','Vietnamese'],
  'russo-one':          ['Latin','Cyrillic'],
  'exo-2':              ['Latin','Latin Ext','Cyrillic','Vietnamese'],
  'dancing-script':     ['Latin','Latin Ext','Vietnamese'],
  'pacifico':           ['Latin','Latin Ext','Cyrillic','Vietnamese'],
  'caveat':             ['Latin','Latin Ext','Cyrillic'],
  'satisfy':            ['Latin'],
  'great-vibes':        ['Latin','Latin Ext'],
  'indie-flower':       ['Latin'],
  'kalam':              ['Latin','Devanagari'],
  'sacramento':         ['Latin','Latin Ext'],
  'jetbrains-mono':     ['Latin','Latin Ext','Cyrillic','Greek'],
  'fira-code':          ['Latin','Latin Ext','Cyrillic','Greek'],
  'source-code-pro':    ['Latin','Latin Ext','Cyrillic','Greek','Vietnamese'],
  'space-mono':         ['Latin'],
  'roboto-mono':        ['Latin','Latin Ext','Cyrillic','Cyrillic Ext','Greek','Greek Ext','Vietnamese'],
  'inconsolata':        ['Latin','Latin Ext','Vietnamese'],
  'ibm-plex-mono':      ['Latin','Latin Ext','Cyrillic'],
  'dm-mono':            ['Latin','Latin Ext'],
  'plus-jakarta-sans':  ['Latin','Latin Ext'],
  'josefin-sans':       ['Latin','Latin Ext'],
  'work-sans':          ['Latin','Latin Ext','Vietnamese'],
  'manrope':            ['Latin','Latin Ext','Cyrillic'],
  'unbounded':          ['Latin','Latin Ext','Cyrillic'],
  'bodoni-moda':        ['Latin','Latin Ext'],
  'fraunces':           ['Latin','Latin Ext'],
  'libre-baskerville':  ['Latin','Latin Ext'],
  'source-serif-4':     ['Latin','Latin Ext','Cyrillic','Greek','Vietnamese'],
  'crimson-pro':        ['Latin','Latin Ext','Vietnamese'],
  'righteous':          ['Latin','Latin Ext'],
  'creepster':          ['Latin'],
  'permanent-marker':   ['Latin'],
  'patrick-hand':       ['Latin','Latin Ext','Vietnamese'],
  'architects-daughter':['Latin'],
  'gloria-hallelujah':  ['Latin'],
  'share-tech-mono':    ['Latin'],
  'anonymous-pro':      ['Latin','Latin Ext','Greek','Cyrillic'],
  'courier-prime':      ['Latin','Latin Ext'],
  'oxanium':            ['Latin','Latin Ext'],
  'mulish':             ['Latin','Latin Ext','Cyrillic','Vietnamese'],
  'karla':              ['Latin','Latin Ext'],
  'rubik':              ['Latin','Latin Ext','Cyrillic','Hebrew','Arabic'],
  'quicksand':          ['Latin','Latin Ext','Vietnamese'],
  'ibm-plex-sans':      ['Latin','Latin Ext','Cyrillic'],
  'zilla-slab':         ['Latin','Latin Ext'],
  'arvo':               ['Latin'],
  'bitter':             ['Latin','Latin Ext','Vietnamese'],
  'domine':             ['Latin','Latin Ext'],
  'alfa-slab-one':      ['Latin'],
  'black-ops-one':      ['Latin'],
  'orbitron':           ['Latin'],
  'press-start-2p':     ['Latin'],
  'teko':               ['Latin','Latin Ext','Devanagari'],
  'parisienne':         ['Latin','Latin Ext'],
  'pinyon-script':      ['Latin'],
  'allura':             ['Latin','Latin Ext'],
  'pt-mono':            ['Latin','Latin Ext','Cyrillic'],
  'overpass-mono':      ['Latin','Latin Ext'],
  'noto-sans':          ['Latin','Latin Ext','Cyrillic','Greek','Vietnamese'],
  'cabinet-grotesk':    ['Latin','Latin Ext'],
  'chivo':              ['Latin','Latin Ext'],
  'albert-sans':        ['Latin','Latin Ext'],
  'italiana':           ['Latin','Latin Ext'],
  'dm-serif-display':   ['Latin','Latin Ext'],
  'vt323':              ['Latin','Latin Ext','Vietnamese'],
  'silkscreen':         ['Latin'],
  'nanum-pen-script':   ['Latin','Korean'],
  'comic-neue':         ['Latin'],
  'fragment-mono':      ['Latin','Latin Ext'],
  'lilita-one':         ['Latin','Latin Ext'],
  'schibsted-grotesk':  ['Latin','Latin Ext'],
  'teachers':           ['Latin','Latin Ext'],
  'reddit-mono':        ['Latin','Latin Ext'],
  'urbanist':           ['Latin','Latin Ext'],
};
function getFontLangs(font) {
  if (FONT_SUBSETS[font.id]) return FONT_SUBSETS[font.id];
  // Fallback: tag-based hints
  const langs = new Set(['Latin']);
  (font.tags||[]).forEach(t => {
    if(/cyrillic/i.test(t)) langs.add('Cyrillic');
    if(/arabic/i.test(t)) langs.add('Arabic');
    if(/hebrew/i.test(t)) langs.add('Hebrew');
    if(/greek/i.test(t)) langs.add('Greek');
    if(/devanagari/i.test(t)) langs.add('Devanagari');
    if(/japanese/i.test(t)) langs.add('Japanese');
    if(/korean/i.test(t)) langs.add('Korean');
    if(/chinese/i.test(t)) langs.add('Chinese');
  });
  return [...langs];
}
