{id:"cuprum",name:"Cuprum",author:"Jovanny Lemonad",cat:"sans-serif",gfamily:"Cuprum:ital,wght@0,400..700;1,400..700",weight:"400",tags:["Condensed","Clean","Modern"],license:"ofl",year:2011,popular:73},
  {id:"days-one",name:"Days One",author:"Jovanny Lemonad",cat:"sans-serif",gfamily:"Days+One",weight:"400",tags:["Headline","Wide","Bold"],license:"ofl",year:2011,popular:64},
  {id:"dosis",name:"Dosis",author:"Impallari Type",cat:"sans-serif",gfamily:"Dosis:wght@200..800",weight:"400",tags:["Rounded","Clean","Futuristic"],license:"ofl",year:2011,popular:81},
  {id:"economica",name:"Economica",author:"Vicente Lamonaca",cat:"sans-serif",gfamily:"Economica:ital,wght@0,400;0,700;1,400;1,700",weight:"400",tags:["Condensed","Technical","Clean"],license:"ofl",year:2011,popular:68},
  {id:"exo",name:"Exo",author:"Natanael Gama",cat:"sans-serif",gfamily:"Exo:ital,wght@0,100..900;1,100..900",weight:"400",tags:["Futuristic","Geometric","Tech"],license:"ofl",year:2011,popular:78},
  {id:"exo-2",name:"Exo 2",author:"Natanael Gama",cat:"sans-serif",gfamily:"Exo+2:ital,wght@0,100..900;1,100..900",weight:"400",tags:["Futuristic","Clean","Variable"],license:"ofl",year:2013,popular:83},
  {id:"federo",name:"Federo",author:"OADType",cat:"sans-serif",gfamily:"Federo",weight:"400",tags:["Display","Vintage","Elegant"],license:"ofl",year:2011,popular:58},
  {id:"fjord-one",name:"Fjord One",author:"Viktoriya Grabowska",cat:"serif",gfamily:"Fjord+One",weight:"400",tags:["Books","Readable","Classic"],license:"ofl",year:2011,popular:61},
  {id:"francois-one",name:"Francois One",author:"Vernon Adams",cat:"sans-serif",gfamily:"Francois+One",weight:"400",tags:["Headline","Gothic","Impact"],license:"ofl",year:2011,popular:72},
  {id:"gentium-plus",name:"Gentium Plus",author:"SIL International",cat:"serif",gfamily:"Gentium+Plus:ital,wght@0,400;0,700;1,400;1,700",weight:"400",tags:["Scholarly","Global","Traditional"],license:"ofl",year:2011,popular:69},
  {id:"gfs-didot",name:"GFS Didot",author:"Greek Font Society",cat:"serif",gfamily:"GFS+Didot",weight:"400",tags:["Greek","Didone","Classic"],license:"ofl",year:2011,popular:59},
  {id:"gloria-hallelujah",name:"Gloria Hallelujah",author:"Kimberly Geswein",cat:"handwriting",gfamily:"Gloria+Hallelujah",weight:"400",tags:["Comic","Marker","Playful"],license:"ofl",year:2011,popular:74},
  {id:"goudy-bookletter-1911",name:"Goudy Bookletter 1911",author:"The League of Moveable Type",cat:"serif",gfamily:"Goudy+Bookletter+1911",weight:"400",tags:["Historical","Book","Elegant"],license:"ofl",year:2011,popular:62},
  {id:"hammersmith-one",name:"Hammersmith One",author:"Nicole Fally",cat:"sans-serif",gfamily:"Hammersmith+One",weight:"400",tags:["Quirky","Bold","Signage"],license:"ofl",year:2011,popular:71},
  {id:"herr-von-muellerhoff",name:"Herr Von Muellerhoff",author:"Sudtipos",cat:"handwriting",gfamily:"Herr+Von+Muellerhoff",weight:"400",tags:["Calligraphy","Ornate","Vintage"],license:"ofl",year:2011,popular:63},
  {id:"iceberg",name:"Iceberg",author:"Cyreal",cat:"display",gfamily:"Iceberg",weight:"400",tags:["Modular","Sharp","Tech"],license:"ofl",year:2012,popular:56},
  {id:"im-fell-english",name:"IM Fell English",author:"Igino Marini",cat:"serif",gfamily:"IM+Fell+English:ital@0;1",weight:"400",tags:["Historical","Vintage","Literature"],license:"ofl",year:2011,popular:65},
  {id:"inika",name:"Inika",author:"Constanza Preti",cat:"serif",gfamily:"Inika:wght@400;700",weight:"400",tags:["Slab","Friendly","Posters"],license:"ofl",year:2011,popular:60},
  {id:"istok-web",name:"Istok Web",author:"Andrey Panov",cat:"sans-serif",gfamily:"Istok+Web:ital,wght@0,400;0,700;1,400;1,700",weight:"400",tags:["Cyrillic","Clean","Neutral"],license:"ofl",year:2011,popular:67},
  {id:"italiana",name:"Italiana",author:"Santiago Orozco",cat:"serif",gfamily:"Italiana",weight:"400",tags:["Fashion","Magazines","Elegant"],license:"ofl",year:2011,popular:76},
  {id:"jacques-francois",name:"Jacques Francois",author:"Cyreal",cat:"serif",gfamily:"Jacques+Francois",weight:"400",tags:["Classic","Book","Academic"],license:"ofl",year:2012,popular:55},
  {id:"josefin-sans",name:"Josefin Sans",author:"Santiago Orozco",cat:"sans-serif",gfamily:"Josefin+Sans:ital,wght@0,100..700;1,100..700",weight:"400",tags:["Geometric","Vintage","Elegant"],license:"ofl",year:2010,popular:88},
  {id:"josefin-slab",name:"Josefin Slab",author:"Santiago Orozco",cat:"serif",gfamily:"Josefin+Slab:ital,wght@0,100..700;1,100..700",weight:"400",tags:["Slab","Geometric","Light"],license:"ofl",year:2011,popular:75},
  {id:"jura",name:"Jura",author:"Ed Merritt",cat:"sans-serif",gfamily:"Jura:wght@300..700",weight:"400",tags:["Eurostyle","Square","Futuristic"],license:"ofl",year:2011,popular:74},
  {id:"karla",name:"Karla",author:"Jonny Pinhorn",cat:"sans-serif",gfamily:"Karla:ital,wght@0,200..800;1,200..800",weight:"400",tags:["Grotesque","Quirky","Clean"],license:"ofl",year:2012,popular:87},
  {id:"kause",name:"Kaushan Script",author:"Impallari Type",cat:"handwriting",gfamily:"Kaushan+Script",weight:"400",tags:["Brush","Energetic","Rustic"],license:"ofl",year:2011,popular:79},
  {id:"khula",name:"Khula",author:"Erin McLaughlin",cat:"sans-serif",gfamily:"Khula:wght@300..800",weight:"400",tags:["Clean","Hindi","Neutral"],license:"ofl",year:2015,popular:66},
  {id:"kreon",name:"Kreon",author:"Julia Petretta",cat:"serif",gfamily:"Kreon:wght@300..700",weight:"400",tags:["Slab","Editorial","Magazine"],license:"ofl",year:2011,popular:68},
  {id:"leckerli-one",name:"Leckerli One",author:"Gesine Todt",cat:"handwriting",gfamily:"Leckerli+One",weight:"400",tags:["Fat","Brush","Playful"],license:"ofl",year:2011,popular:70},
  {id:"ledger",name:"Ledger",author:"Denis Masharov",cat:"serif",gfamily:"Ledger",weight:"400",tags:["Editorial","Robust","Newspaper"],license:"ofl",year:2011,popular:63},
  {id:"lexend",name:"Lexend",author:"Thomas Jockin",cat:"sans-serif",gfamily:"Lexend:wght@100..900",weight:"400",tags:["Education","Readable","Clean"],license:"ofl",year:2019,popular:86},
  {id:"libre-franklin",name:"Libre Franklin",author:"Impallari Type",cat:"sans-serif",gfamily:"Libre+Franklin:ital,wght@0,100..900;1,100..900",weight:"400",tags:["Grotesque","American","Clean"],license:"ofl",year:2016,popular:84},
  {id:"limelight",name:"Limelight",author:"Sorkin Type",cat:"display",gfamily:"Limelight",weight:"400",tags:["Art-Deco","Cinema","Retro"],license:"ofl",year:2011,popular:65},
  {id:"mako",name:"Mako",author:"Vernon Adams",cat:"sans-serif",gfamily:"Mako",weight:"400",tags:["Clean","Ui","Neutral"],license:"ofl",year:2011,popular:57},
  {id:"marcellus",name:"Marcellus",author:"Astigmatic",cat:"serif",gfamily:"Marcellus",weight:"400",tags:["Roman","Luxury","Classic"],license:"ofl",year:2012,popular:72},
  {id:"maven-pro",name:"Maven Pro",author:"Joe Prince",cat:"sans-serif",gfamily:"Maven+Pro:wght@400..900",weight:"400",tags:["Curved","Modern","Ui"],license:"ofl",year:2011,popular:82},
  {id:"megrim",name:"Megrim",author:"Daniel Johnson",cat:"display",gfamily:"Megrim",weight:"400",tags:["Experimental","Futuristic","Lines"],license:"ofl",year:2011,popular:61},
  {id:"merriweather-sans",name:"Merriweather Sans",author:"Sorkin Type",cat:"sans-serif",gfamily:"Merriweather+Sans:ital,wght@0,300..800;1,300..800",weight:"400",tags:["Screen","Robust","Clean"],license:"ofl",year:2013,popular:80},
  {id:"michroma",name:"Michroma",author:"Vernon Adams",cat:"sans-serif",gfamily:"Michroma",weight:"400",tags:["Square","Extended","Tech"],license:"ofl",year:2011,popular:62},
  {id:"modern-antiqua",name:"Modern Antiqua",author:"Wojciech Kalinowski",cat:"serif",gfamily:"Modern+Antiqua",weight:"400",tags:["Quirky","Vintage","Book"],license:"ofl",year:2011,popular:56},
  {id:"monda",name:"Monda",author:"Vernon Adams",cat:"sans-serif",gfamily:"Monda:wght@400;700",weight:"400",tags:["Clean","Ui","Responsive"],license:"ofl",year:2012,popular:67},
  {id:"news-cycle",name:"News Cycle",author:"Nathan Willis",cat:"sans-serif",gfamily:"News+Cycle:wght@400;700",weight:"400",tags:["Newspaper","Condensed","Classic"],license:"ofl",year:2011,popular:69},
  {id:"noto-sans",name:"Noto Sans",author:"Google",cat:"sans-serif",gfamily:"Noto+Sans:ital,wght@0,100..900;1,100..900",weight:"400",tags:["Global","Universal","Clean"],license:"ofl",year:2012,popular:95},
  {id:"orbitron",name:"Orbitron",author:"Matt McInerney",cat:"sans-serif",gfamily:"Orbitron:wght@400..900",weight:"400",tags:["Sci-Fi","Futuristic","Tech"],license:"ofl",year:2011,popular:80},
  {id:"overpass",name:"Overpass",author:"Red Hat",cat:"sans-serif",gfamily:"Overpass:ital,wght@0,100..900;1,100..900",weight:"400",tags:["Corporate","Signage","Clean"],license:"ofl",year:2016,popular:79},
  {id:"oxygen",name:"Oxygen",author:"Vernon Adams",cat:"sans-serif",gfamily:"Oxygen:wght@300;400;700",weight:"400",tags:["Kde","Linux","Ui"],license:"ofl",year:2011,popular:82},
  {id:"pathway-gothic-one",name:"Pathway Gothic One",author:"Eduardo Tunni",cat:"sans-serif",gfamily:"Pathway+Gothic+One",weight:"400",tags:["Condensed","Headline","Editorial"],license:"ofl",year:2013,popular:71},
  {id:"paytone-one",name:"Paytone One",author:"Vernon Adams",cat:"sans-serif",gfamily:"Paytone+One",weight:"400",tags:["Heavy","Display","Casual"],license:"ofl",year:2011,popular:73},
  {id:"philosopher",name:"Philosopher",author:"Jovanny Lemonad",cat:"sans-serif",gfamily:"Philosopher:ital,wght@0,400;0,700;1,400;1,700",weight:"400",tags:["Elegant","Ornate","Cyrillic"],license:"ofl",year:2011,popular:75},
  {id:"play",name:"Play",author:"Evgeny Tkachuk",cat:"sans-serif",gfamily:"Play:wght@400;700",weight:"400",tags:["Tech","Clean","Cyrillic"],license:"ofl",year:2011,popular:77}
];