const FONTS_BASE=[
  {id:"inter",name:"Inter",author:"Rasmus Andersson",cat:"sans-serif",gfamily:"Inter:wght@300;400;500;700",weight:"400",tags:["Clean","UI","Neutral"],license:"ofl",year:2017,popular:99},
  {id:"montserrat",name:"Montserrat",author:"Julieta Ulanovsky",cat:"sans-serif",gfamily:"Montserrat:wght@400;700;900",weight:"700",tags:["Geometric","Modern","Bold"],license:"ofl",year:2011,popular:98},
  {id:"open-sans",name:"Open Sans",author:"Steve Matteson",cat:"sans-serif",gfamily:"Open+Sans:wght@300;400;600;700",weight:"400",tags:["Humanist","Clean","Versatile"],license:"apache",year:2011,popular:97},
  {id:"lato",name:"Lato",author:"Lukasz Dziedzic",cat:"sans-serif",gfamily:"Lato:wght@300;400;700;900",weight:"400",tags:["Humanist","Warm","Corporate"],license:"ofl",year:2010,popular:96},
  {id:"poppins",name:"Poppins",author:"Indian Type Foundry",cat:"sans-serif",gfamily:"Poppins:wght@400;600;700;800",weight:"600",tags:["Geometric","Rounded","Modern"],license:"ofl",year:2014,popular:97},
  {id:"nunito",name:"Nunito",author:"Vernon Adams",cat:"sans-serif",gfamily:"Nunito:wght@400;600;700;800",weight:"400",tags:["Rounded","Friendly","UI"],license:"ofl",year:2014,popular:89},
  {id:"raleway",name:"Raleway",author:"Matt McInerney",cat:"sans-serif",gfamily:"Raleway:wght@200;400;700;900",weight:"300",tags:["Elegant","Thin","Fashion"],license:"ofl",year:2010,popular:88},
  {id:"oswald",name:"Oswald",author:"Vernon Adams",cat:"sans-serif",gfamily:"Oswald:wght@400;500;700",weight:"700",tags:["Condensed","Strong","Heading"],license:"ofl",year:2011,popular:93},
  {id:"roboto",name:"Roboto",author:"Christian Robertson",cat:"sans-serif",gfamily:"Roboto:wght@300;400;700;900",weight:"400",tags:["Android","Neutral","System"],license:"apache",year:2011,popular:99},
  {id:"dm-sans",name:"DM Sans",author:"Colophon Foundry",cat:"sans-serif",gfamily:"DM+Sans:wght@300;400;500;700",weight:"400",tags:["Optical","Clean","Editorial"],license:"ofl",year:2019,popular:87},
  {id:"outfit",name:"Outfit",author:"Rodrigo Fuenzalida",cat:"sans-serif",gfamily:"Outfit:wght@300;400;600;700;800",weight:"400",tags:["Geometric","Modern","Variable"],license:"ofl",year:2021,popular:83},
  {id:"figtree",name:"Figtree",author:"Erik Kennedy",cat:"sans-serif",gfamily:"Figtree:wght@300;400;600;700;800",weight:"400",tags:["Geometric","Friendly","UI"],license:"ofl",year:2022,popular:80},
  {id:"barlow",name:"Barlow",author:"Jeremy Tribby",cat:"sans-serif",gfamily:"Barlow:wght@300;400;600;700",weight:"400",tags:["Grotesque","Condensed","Modern"],license:"ofl",year:2017,popular:81},
  {id:"playfair-display",name:"Playfair Display",author:"Claus Eggers Sørensen",cat:"serif",gfamily:"Playfair+Display:ital,wght@0,400;0,700;0,900;1,400;1,900",weight:"700",tags:["Elegant","Editorial","Luxury"],license:"ofl",year:2011,popular:94},
  {id:"merriweather",name:"Merriweather",author:"Eben Sorkin",cat:"serif",gfamily:"Merriweather:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Reading","Sturdy","News"],license:"ofl",year:2011,popular:90},
  {id:"lora",name:"Lora",author:"Cyreal",cat:"serif",gfamily:"Lora:ital,wght@0,400;0,700;1,400;1,700",weight:"400",tags:["Calligraphic","Literary","Italic"],license:"ofl",year:2011,popular:88},
  {id:"cormorant-garamond",name:"Cormorant Garamond",author:"Christian Thalmann",cat:"serif",gfamily:"Cormorant+Garamond:ital,wght@0,300;0,400;0,700;1,300;1,400",weight:"300",tags:["Luxury","Display","Thin"],license:"ofl",year:2015,popular:86},
  {id:"eb-garamond",name:"EB Garamond",author:"Georg Duffner",cat:"serif",gfamily:"EB+Garamond:ital,wght@0,400;0,700;1,400",weight:"400",tags:["Classic","Oldstyle","Books"],license:"ofl",year:2010,popular:81},
  {id:"cinzel",name:"Cinzel",author:"Natanael Gama",cat:"serif",gfamily:"Cinzel:wght@400;700;900",weight:"700",tags:["Roman","Display","Classic"],license:"ofl",year:2012,popular:84},
  {id:"spectral",name:"Spectral",author:"Production Type",cat:"serif",gfamily:"Spectral:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Literary","Variable","Reading"],license:"ofl",year:2017,popular:78},
  {id:"pt-serif",name:"PT Serif",author:"ParaType",cat:"serif",gfamily:"PT+Serif:ital,wght@0,400;0,700;1,400",weight:"400",tags:["Humanist","Newspaper","Classic"],license:"ofl",year:2010,popular:82},
  {id:"bebas-neue",name:"Bebas Neue",author:"Ryoichi Tsunekawa",cat:"display",gfamily:"Bebas+Neue",weight:"400",tags:["All-Caps","Strong","Poster"],license:"ofl",year:2010,popular:92},
  {id:"abril-fatface",name:"Abril Fatface",author:"Veronika Burian",cat:"display",gfamily:"Abril+Fatface",weight:"400",tags:["Titling","Bold","Magazine"],license:"ofl",year:2011,popular:87},
  {id:"syne",name:"Syne",author:"Lucas Descroix",cat:"display",gfamily:"Syne:wght@400;700;800",weight:"800",tags:["Experimental","Variable","Modern"],license:"ofl",year:2017,popular:83},
  {id:"space-grotesk",name:"Space Grotesk",author:"Florian Karsten",cat:"display",gfamily:"Space+Grotesk:wght@300;400;700",weight:"700",tags:["Quirky","Tech","Modern"],license:"ofl",year:2018,popular:85},
  {id:"fredoka",name:"Fredoka",author:"Milena Brandão",cat:"display",gfamily:"Fredoka:wght@300;400;600;700",weight:"600",tags:["Rounded","Playful","Variable"],license:"ofl",year:2011,popular:82},
  {id:"bangers",name:"Bangers",author:"Vernon Adams",cat:"display",gfamily:"Bangers",weight:"400",tags:["Comic","Impact","Casual"],license:"ofl",year:2011,popular:81},
  {id:"russo-one",name:"Russo One",author:"Jovanny Lemonad",cat:"display",gfamily:"Russo+One",weight:"400",tags:["Cyrillic","Strong","Poster"],license:"ofl",year:2011,popular:80},
  {id:"exo-2",name:"Exo 2",author:"Natanael Gama",cat:"display",gfamily:"Exo+2:wght@300;400;700;900",weight:"700",tags:["Sci-Fi","Variable","Tech"],license:"ofl",year:2013,popular:81},
  {id:"dancing-script",name:"Dancing Script",author:"Impallari Type",cat:"handwriting",gfamily:"Dancing+Script:wght@400;700",weight:"700",tags:["Calligraphic","Casual","Bouncy"],license:"ofl",year:2011,popular:90},
  {id:"pacifico",name:"Pacifico",author:"Vernon Adams",cat:"handwriting",gfamily:"Pacifico",weight:"400",tags:["Retro","Script","Fun"],license:"ofl",year:2011,popular:89},
  {id:"caveat",name:"Caveat",author:"Pablo Impallari",cat:"handwriting",gfamily:"Caveat:wght@400;700",weight:"400",tags:["Natural","Informal","Handwritten"],license:"ofl",year:2016,popular:84},
  {id:"satisfy",name:"Satisfy",author:"Sideshow",cat:"handwriting",gfamily:"Satisfy",weight:"400",tags:["Script","Elegant","Calligraphy"],license:"apache",year:2011,popular:80},
  {id:"great-vibes",name:"Great Vibes",author:"TypeSETit",cat:"handwriting",gfamily:"Great+Vibes",weight:"400",tags:["Calligraphy","Wedding","Formal"],license:"ofl",year:2012,popular:79},
  {id:"indie-flower",name:"Indie Flower",author:"Kimberly Geswein",cat:"handwriting",gfamily:"Indie+Flower",weight:"400",tags:["Bubble","Friendly","Casual"],license:"ofl",year:2011,popular:82},
  {id:"kalam",name:"Kalam",author:"Indian Type Foundry",cat:"handwriting",gfamily:"Kalam:wght@300;400;700",weight:"400",tags:["Devanagari","Casual","Natural"],license:"ofl",year:2014,popular:76},
  {id:"sacramento",name:"Sacramento",author:"Astigmatic",cat:"handwriting",gfamily:"Sacramento",weight:"400",tags:["Formal","Thin","Calligraphy"],license:"ofl",year:2012,popular:77},
  {id:"jetbrains-mono",name:"JetBrains Mono",author:"JetBrains",cat:"monospace",gfamily:"JetBrains+Mono:wght@400;700",weight:"400",tags:["Code","Ligatures","Developer"],license:"ofl",year:2020,popular:89},
  {id:"fira-code",name:"Fira Code",author:"Nikita Prokopov",cat:"monospace",gfamily:"Fira+Code:wght@300;400;500;700",weight:"400",tags:["Ligatures","Dev","Mozilla"],license:"ofl",year:2014,popular:88},
  {id:"source-code-pro",name:"Source Code Pro",author:"Paul D. Hunt",cat:"monospace",gfamily:"Source+Code+Pro:wght@400;500;700",weight:"500",tags:["Adobe","Code","Clean"],license:"ofl",year:2012,popular:88},
  {id:"space-mono",name:"Space Mono",author:"Colophon Foundry",cat:"monospace",gfamily:"Space+Mono:wght@400;700",weight:"400",tags:["Geometric","Display","Retro"],license:"ofl",year:2016,popular:84},
  {id:"roboto-mono",name:"Roboto Mono",author:"Christian Robertson",cat:"monospace",gfamily:"Roboto+Mono:wght@300;400;700",weight:"400",tags:["Android","System","Neutral"],license:"apache",year:2015,popular:86},
  {id:"inconsolata",name:"Inconsolata",author:"Raph Levien",cat:"monospace",gfamily:"Inconsolata:wght@400;700",weight:"400",tags:["Classic","Compact","Code"],license:"ofl",year:2006,popular:83},
  {id:"ibm-plex-mono",name:"IBM Plex Mono",author:"Bold Monday",cat:"monospace",gfamily:"IBM+Plex+Mono:wght@400;500;700",weight:"400",tags:["IBM","Corporate","Code"],license:"ofl",year:2017,popular:82},
  {id:"dm-mono",name:"DM Mono",author:"Colophon Foundry",cat:"monospace",gfamily:"DM+Mono:wght@300;400;500",weight:"400",tags:["Editorial","Light","Design"],license:"ofl",year:2019,popular:82},
  {id:"plus-jakarta-sans",name:"Plus Jakarta Sans",author:"Tokotype",cat:"sans-serif",gfamily:"Plus+Jakarta+Sans:wght@300;400;500;600;700;800",weight:"400",tags:["Modern","UI","Clean"],license:"ofl",year:2020,popular:81},
  {id:"josefin-sans",name:"Josefin Sans",author:"Santiago Orozco",cat:"sans-serif",gfamily:"Josefin+Sans:wght@300;400;600;700",weight:"600",tags:["Geometric","Elegant","Heading"],license:"ofl",year:2010,popular:84},
  {id:"work-sans",name:"Work Sans",author:"Wei Huang",cat:"sans-serif",gfamily:"Work+Sans:wght@300;400;500;600;700",weight:"400",tags:["Grotesque","Clean","Variable"],license:"ofl",year:2015,popular:83},
  {id:"manrope",name:"Manrope",author:"Mikhail Sharanda",cat:"sans-serif",gfamily:"Manrope:wght@300;400;500;600;700;800",weight:"400",tags:["Modern","Variable","UI"],license:"ofl",year:2018,popular:80},
  {id:"unbounded",name:"Unbounded",author:"Uppertype",cat:"display",gfamily:"Unbounded:wght@300;400;500;600;700;800",weight:"700",tags:["Wide","Bold","Web3"],license:"ofl",year:2022,popular:78},
  {id:"bodoni-moda",name:"Bodoni Moda",author:"Indestructible Type",cat:"serif",gfamily:"Bodoni+Moda:ital,wght@0,400;0,700;0,900;1,400",weight:"700",tags:["Didone","Fashion","Luxury"],license:"ofl",year:2020,popular:79},
  {id:"fraunces",name:"Fraunces",author:"Undercase Type",cat:"serif",gfamily:"Fraunces:ital,wght@0,300;0,400;0,700;1,300;1,400",weight:"400",tags:["Optical","Soft","Literary"],license:"ofl",year:2020,popular:76},
  {id:"libre-baskerville",name:"Libre Baskerville",author:"Impallari Type",cat:"serif",gfamily:"Libre+Baskerville:ital,wght@0,400;0,700;1,400",weight:"400",tags:["Classic","Reading","Book"],license:"ofl",year:2012,popular:82},
  {id:"source-serif-4",name:"Source Serif 4",author:"Frank Grießhammer",cat:"serif",gfamily:"Source+Serif+4:ital,opsz,wght@0,8,300;0,8,400;0,8,700;1,8,400",weight:"400",tags:["Adobe","Variable","Reading"],license:"ofl",year:2021,popular:77},
  {id:"crimson-pro",name:"Crimson Pro",author:"Jacques Le Bailly",cat:"serif",gfamily:"Crimson+Pro:ital,wght@0,400;0,600;1,400",weight:"400",tags:["Humanist","Variable","Books"],license:"ofl",year:2019,popular:75},
  {id:"righteous",name:"Righteous",author:"Astigmatic",cat:"display",gfamily:"Righteous",weight:"400",tags:["Retro","Bold","Fun"],license:"ofl",year:2012,popular:78},
  {id:"creepster",name:"Creepster",author:"Kimberly Geswein",cat:"display",gfamily:"Creepster",weight:"400",tags:["Horror","Halloween","Spooky"],license:"ofl",year:2012,popular:74},
  {id:"permanent-marker",name:"Permanent Marker",author:"Font Diner",cat:"handwriting",gfamily:"Permanent+Marker",weight:"400",tags:["Marker","Casual","Bold"],license:"apache",year:2010,popular:81},
  {id:"patrick-hand",name:"Patrick Hand",author:"Patrick Wagesreiter",cat:"handwriting",gfamily:"Patrick+Hand",weight:"400",tags:["Natural","Casual","Clean"],license:"ofl",year:2010,popular:76},
  {id:"architects-daughter",name:"Architects Daughter",author:"Kimberly Geswein",cat:"handwriting",gfamily:"Architects+Daughter",weight:"400",tags:["Sketch","Blueprint","Casual"],license:"apache",year:2010,popular:79},
  {id:"gloria-hallelujah",name:"Gloria Hallelujah",author:"Kimberly Geswein",cat:"handwriting",gfamily:"Gloria+Hallelujah",weight:"400",tags:["Comic","Expressive","Fun"],license:"apache",year:2010,popular:77},
  {id:"share-tech-mono",name:"Share Tech Mono",author:"Carrois Type Design",cat:"monospace",gfamily:"Share+Tech+Mono",weight:"400",tags:["Tech","Hacker","Terminal"],license:"ofl",year:2012,popular:74},
  {id:"anonymous-pro",name:"Anonymous Pro",author:"Mark Simonson",cat:"monospace",gfamily:"Anonymous+Pro:wght@400;700",weight:"400",tags:["Code","Classic","Terminal"],license:"ofl",year:2009,popular:75},
  {id:"courier-prime",name:"Courier Prime",author:"Quote-Unquote Apps",cat:"monospace",gfamily:"Courier+Prime:ital,wght@0,400;0,700;1,400",weight:"400",tags:["Typewriter","Screenplay","Classic"],license:"ofl",year:2015,popular:73},
  {id:"oxanium",name:"Oxanium",author:"Severin Meyer",cat:"display",gfamily:"Oxanium:wght@300;400;600;700;800",weight:"700",tags:["Sci-Fi","Gaming","Tech"],license:"ofl",year:2019,popular:72},
  {id:"mulish",name:"Mulish",author:"Vernon Adams",cat:"sans-serif",gfamily:"Mulish:wght@300;400;500;600;700;900",weight:"400",tags:["Humanist","Clean","Versatile"],license:"ofl",year:2019,popular:82},
  {id:"karla",name:"Karla",author:"Jonathan Pinhorn",cat:"sans-serif",gfamily:"Karla:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Grotesque","Informal","Variable"],license:"ofl",year:2012,popular:79},
  {id:"rubik",name:"Rubik",author:"Hubert & Fischer",cat:"sans-serif",gfamily:"Rubik:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Rounded","Variable","UI"],license:"ofl",year:2015,popular:86},
  {id:"quicksand",name:"Quicksand",author:"Andrew Paglinawan",cat:"sans-serif",gfamily:"Quicksand:wght@300;400;500;600;700",weight:"400",tags:["Rounded","Friendly","Display"],license:"ofl",year:2008,popular:84},
  {id:"ibm-plex-sans",name:"IBM Plex Sans",author:"Bold Monday",cat:"sans-serif",gfamily:"IBM+Plex+Sans:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["IBM","Corporate","Technical"],license:"ofl",year:2017,popular:83},
  {id:"zilla-slab",name:"Zilla Slab",author:"Typotheque",cat:"serif",gfamily:"Zilla+Slab:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Slab","Mozilla","Modern"],license:"ofl",year:2017,popular:76},
  {id:"arvo",name:"Arvo",author:"Anton Koovit",cat:"serif",gfamily:"Arvo:ital,wght@0,400;0,700;1,400",weight:"400",tags:["Slab","Sturdy","Reading"],license:"ofl",year:2010,popular:80},
  {id:"bitter",name:"Bitter",author:"Sol Matas",cat:"serif",gfamily:"Bitter:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Slab","Variable","News"],license:"ofl",year:2011,popular:78},
  {id:"domine",name:"Domine",author:"Impallari Type",cat:"serif",gfamily:"Domine:wght@400;700",weight:"400",tags:["Sturdy","Reading","Book"],license:"ofl",year:2013,popular:72},
  {id:"alfa-slab-one",name:"Alfa Slab One",author:"JM Sole",cat:"display",gfamily:"Alfa+Slab+One",weight:"400",tags:["Slab","Bold","Poster"],license:"ofl",year:2012,popular:74},
  {id:"black-ops-one",name:"Black Ops One",author:"James Grieshaber",cat:"display",gfamily:"Black+Ops+One",weight:"400",tags:["Military","Bold","Gaming"],license:"ofl",year:2012,popular:77},
  {id:"orbitron",name:"Orbitron",author:"Matt McInerney",cat:"display",gfamily:"Orbitron:wght@400;500;700;900",weight:"700",tags:["Futuristic","Geometric","Sci-Fi"],license:"ofl",year:2009,popular:80},
  {id:"press-start-2p",name:"Press Start 2P",author:"CodeMan38",cat:"display",gfamily:"Press+Start+2P",weight:"400",tags:["Pixel","Retro","Gaming"],license:"ofl",year:2012,popular:82},
  {id:"teko",name:"Teko",author:"Indian Type Foundry",cat:"display",gfamily:"Teko:wght@300;400;500;600;700",weight:"600",tags:["Condensed","Devanagari","Heading"],license:"ofl",year:2015,popular:78},
  {id:"parisienne",name:"Parisienne",author:"Astigmatic",cat:"handwriting",gfamily:"Parisienne",weight:"400",tags:["Script","French","Elegant"],license:"ofl",year:2012,popular:74},
  {id:"pinyon-script",name:"Pinyon Script",author:"Nicole Fally",cat:"handwriting",gfamily:"Pinyon+Script",weight:"400",tags:["Calligraphy","Formal","Wedding"],license:"ofl",year:2012,popular:73},
  {id:"allura",name:"Allura",author:"TypeSETit",cat:"handwriting",gfamily:"Allura",weight:"400",tags:["Script","Formal","Elegant"],license:"ofl",year:2011,popular:72},
  {id:"pt-mono",name:"PT Mono",author:"ParaType",cat:"monospace",gfamily:"PT+Mono",weight:"400",tags:["Cyrillic","Classic","Code"],license:"ofl",year:2009,popular:73},
  {id:"overpass-mono",name:"Overpass Mono",author:"Delve Withrington",cat:"monospace",gfamily:"Overpass+Mono:wght@300;400;600;700",weight:"400",tags:["Open Source","Variable","Code"],license:"ofl",year:2016,popular:71},
  {id:"noto-sans",name:"Noto Sans",author:"Google",cat:"sans-serif",gfamily:"Noto+Sans:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Universal","Multilingual","Google"],license:"ofl",year:2012,popular:88},
  {id:"cabinet-grotesk",name:"Cabinet Grotesk",author:"Fontshare",cat:"sans-serif",gfamily:"Cabinet+Grotesk:wght@300;400;500;600;700;800",weight:"500",tags:["Grotesque","Modern","Variable"],license:"ofl",year:2022,popular:79},
  {id:"chivo",name:"Chivo",author:"Héctor Gatti",cat:"sans-serif",gfamily:"Chivo:ital,wght@0,300;0,400;0,700;0,900;1,400",weight:"400",tags:["Grotesque","Editorial","Variable"],license:"ofl",year:2013,popular:76},
  {id:"albert-sans",name:"Albert Sans",author:"Andreas Rasmussen",cat:"sans-serif",gfamily:"Albert+Sans:ital,wght@0,300;0,400;0,500;0,700;1,400",weight:"400",tags:["Geometric","Clean","Variable"],license:"ofl",year:2022,popular:74},
  {id:"italiana",name:"Italiana",author:"Alicia Carvalho",cat:"serif",gfamily:"Italiana",weight:"400",tags:["Didone","Elegant","Fashion"],license:"ofl",year:2012,popular:73},
  {id:"dm-serif-display",name:"DM Serif Display",author:"Colophon Foundry",cat:"serif",gfamily:"DM+Serif+Display:ital@0;1",weight:"400",tags:["Editorial","Contrast","Display"],license:"ofl",year:2019,popular:80},
  {id:"vt323",name:"VT323",author:"Peter Hull",cat:"display",gfamily:"VT323",weight:"400",tags:["Pixel","Terminal","Retro"],license:"ofl",year:2014,popular:75},
  {id:"silkscreen",name:"Silkscreen",author:"Jason Kottke",cat:"display",gfamily:"Silkscreen:wght@400;700",weight:"400",tags:["Pixel","Bitmap","Gaming"],license:"ofl",year:2021,popular:72},
  {id:"nanum-pen-script",name:"Nanum Pen Script",author:"Sandoll",cat:"handwriting",gfamily:"Nanum+Pen+Script",weight:"400",tags:["Korean","Handwritten","Casual"],license:"ofl",year:2012,popular:70},
  {id:"comic-neue",name:"Comic Neue",author:"Craig Rozynski",cat:"handwriting",gfamily:"Comic+Neue:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Comic","Friendly","Casual"],license:"ofl",year:2014,popular:71},
  {id:"bad-script",name:"Bad Script",author:"Jovanny Lemonad",cat:"handwriting",gfamily:"Bad+Script",weight:"400",tags:["Cyrillic","Handwritten","Rough"],license:"ofl",year:2011,popular:70},
  {id:"mr-dafoe",name:"Mr Dafoe",author:"Astigmatic",cat:"handwriting",gfamily:"Mr+Dafoe",weight:"400",tags:["Script","Signature","Formal"],license:"ofl",year:2012,popular:73},
  {id:"italianno",name:"Italianno",author:"Astigmatic",cat:"handwriting",gfamily:"Italianno",weight:"400",tags:["Italic","Calligraphy","Elegant"],license:"ofl",year:2012,popular:71},
  {id:"cedarville-cursive",name:"Cedarville Cursive",author:"Tanya David",cat:"handwriting",gfamily:"Cedarville+Cursive",weight:"400",tags:["Cursive","Casual","Clean"],license:"ofl",year:2011,popular:67},
  {id:"covered-by-your-grace",name:"Covered By Your Grace",author:"Kimberly Geswein",cat:"handwriting",gfamily:"Covered+By+Your+Grace",weight:"400",tags:["Casual","Handwritten","Friendly"],license:"ofl",year:2011,popular:68},
  {id:"just-another-hand",name:"Just Another Hand",author:"Astigmatic",cat:"handwriting",gfamily:"Just+Another+Hand",weight:"400",tags:["Casual","Print","Handwritten"],license:"ofl",year:2011,popular:66},
  {id:"reenie-beanie",name:"Reenie Beanie",author:"Astigmatic",cat:"handwriting",gfamily:"Reenie+Beanie",weight:"400",tags:["Casual","Handwritten","Thin"],license:"ofl",year:2011,popular:69},
  {id:"rock-salt",name:"Rock Salt",author:"Font Diner",cat:"handwriting",gfamily:"Rock+Salt",weight:"400",tags:["Rough","Marker","Edgy"],license:"apache",year:2010,popular:72},
  {id:"give-you-glory",name:"Give You Glory",author:"Kimberly Geswein",cat:"handwriting",gfamily:"Give+You+Glory",weight:"400",tags:["Script","Casual","Handwritten"],license:"ofl",year:2011,popular:65},
  {id:"walter-turncoat",name:"Walter Turncoat",author:"Astigmatic",cat:"handwriting",gfamily:"Walter+Turncoat",weight:"400",tags:["Casual","Print","Handwritten"],license:"apache",year:2010,popular:64},
  {id:"felipa",name:"Felipa",author:"Sorkin Type",cat:"handwriting",gfamily:"Felipa",weight:"400",tags:["Script","Handwritten","Casual"],license:"ofl",year:2012,popular:63},
  {id:"caveat-brush",name:"Caveat Brush",author:"Pablo Impallari",cat:"handwriting",gfamily:"Caveat+Brush",weight:"400",tags:["Brush","Casual","Rough"],license:"ofl",year:2016,popular:75},
  {id:"marck-script",name:"Marck Script",author:"Alexei Vanyashin",cat:"handwriting",gfamily:"Marck+Script",weight:"400",tags:["Cyrillic","Script","Casual"],license:"ofl",year:2012,popular:72},
  {id:"annie-use-your-telescope",name:"Annie Use Your Telescope",author:"Astigmatic",cat:"handwriting",gfamily:"Annie+Use+Your+Telescope",weight:"400",tags:["Casual","Playful","Handwritten"],license:"apache",year:2010,popular:67},
  {id:"kristi",name:"Kristi",author:"Birgit Pulk",cat:"handwriting",gfamily:"Kristi",weight:"400",tags:["Script","Cursive","Elegant"],license:"ofl",year:2011,popular:68},
  {id:"homemade-apple",name:"Homemade Apple",author:"Font Diner",cat:"handwriting",gfamily:"Homemade+Apple",weight:"400",tags:["Script","Casual","Fun"],license:"apache",year:2010,popular:71},
  {id:"loved-by-the-king",name:"Loved by the King",author:"Astigmatic",cat:"handwriting",gfamily:"Loved+by+the+King",weight:"400",tags:["Script","Vintage","Romantic"],license:"apache",year:2010,popular:66},
  {id:"la-belle-aurore",name:"La Belle Aurore",author:"Astigmatic",cat:"handwriting",gfamily:"La+Belle+Aurore",weight:"400",tags:["Script","French","Romantic"],license:"apache",year:2010,popular:68},
  {id:"ms-madi",name:"Ms Madi",author:"Robert Leuschke",cat:"handwriting",gfamily:"Ms+Madi",weight:"400",tags:["Script","Elegant","Formal"],license:"ofl",year:2021,popular:67},
  {id:"style-script",name:"Style Script",author:"Robert Leuschke",cat:"handwriting",gfamily:"Style+Script",weight:"400",tags:["Script","Calligraphy","Elegant"],license:"ofl",year:2021,popular:65},
  {id:"ephesis",name:"Ephesis",author:"Robert Leuschke",cat:"handwriting",gfamily:"Ephesis",weight:"400",tags:["Script","Casual","Flowing"],license:"ofl",year:2021,popular:64},
  {id:"fragment-mono",name:"Fragment Mono",author:"Nico Stubler",cat:"monospace",gfamily:"Fragment+Mono:ital@0;1",weight:"400",tags:["Minimal","Code","Modern"],license:"ofl",year:2023,popular:69},
  {id:"lilita-one",name:"Lilita One",author:"Rodrigo Fuenzalida",cat:"display",gfamily:"Lilita+One",weight:"400",tags:["Bold","Rounded","Latin"],license:"ofl",year:2011,popular:76},
  {id:"schibsted-grotesk",name:"Schibsted Grotesk",author:"Schibsted",cat:"sans-serif",gfamily:"Schibsted+Grotesk:ital,wght@0,400;0,500;0,700;0,900;1,400",weight:"400",tags:["Grotesque","News","Editorial"],license:"ofl",year:2023,popular:68},
  {id:"teachers",name:"Teachers",author:"Omnibus-Type",cat:"sans-serif",gfamily:"Teachers:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400",weight:"400",tags:["Humanist","Friendly","Variable"],license:"ofl",year:2023,popular:67},
  {id:"reddit-mono",name:"Reddit Mono",author:"Reddit",cat:"monospace",gfamily:"Reddit+Mono:wght@300;400;500;600;700",weight:"400",tags:["Code","Neutral","Variable"],license:"ofl",year:2024,popular:70},
  {id:"urbanist",name:"Urbanist",author:"Corey Hu",cat:"sans-serif",gfamily:"Urbanist:ital,wght@0,300;0,400;0,500;0,600;0,700;1,400",weight:"400",tags:["Geometric","Clean","Variable"],license:"ofl",year:2020,popular:78},
  {id:"bungee",name:"Bungee",author:"David Jonathan Ross",cat:"display",gfamily:"Bungee",weight:"400",tags:["Bold","Urban","Poster"],license:"ofl",year:2015,popular:76},
  {id:"boogaloo",name:"Boogaloo",author:"John Vargas Beltrán",cat:"display",gfamily:"Boogaloo",weight:"400",tags:["Retro","Fun","Casual"],license:"ofl",year:2012,popular:75},
  {id:"audiowide",name:"Audiowide",author:"Astigmatic",cat:"display",gfamily:"Audiowide",weight:"400",tags:["Tech","Futuristic","Gaming"],license:"ofl",year:2012,popular:72},
  {id:"graduate",name:"Graduate",author:"Eduardo Tunni",cat:"display",gfamily:"Graduate",weight:"400",tags:["College","Varsity","Bold"],license:"ofl",year:2013,popular:73},
  {id:"titan-one",name:"Titan One",author:"Rodrigo Fuenzalida",cat:"display",gfamily:"Titan+One",weight:"400",tags:["Bold","Rounded","Fun"],license:"ofl",year:2013,popular:71},
  {id:"turret-road",name:"Turret Road",author:"Ultracuts",cat:"display",gfamily:"Turret+Road:wght@400;700",weight:"700",tags:["Futuristic","Tech","Sci-Fi"],license:"ofl",year:2019,popular:68},
  {id:"bowlby-one",name:"Bowlby One",author:"Cyreal",cat:"display",gfamily:"Bowlby+One",weight:"400",tags:["Bold","Condensed","Poster"],license:"ofl",year:2011,popular:70},
  {id:"shrikhand",name:"Shrikhand",author:"Jonny Pinhorn",cat:"display",gfamily:"Shrikhand",weight:"400",tags:["Bold","Gujarati","Display"],license:"ofl",year:2016,popular:69},
  {id:"monoton",name:"Monoton",author:"Vernon Adams",cat:"display",gfamily:"Monoton",weight:"400",tags:["Retro","Neon","Decorative"],license:"ofl",year:2011,popular:68},
  {id:"modak",name:"Modak",author:"Ek Type",cat:"display",gfamily:"Modak",weight:"400",tags:["Bold","Devanagari","Playful"],license:"ofl",year:2015,popular:67},
  {id:"vast-shadow",name:"Vast Shadow",author:"Astigmatic",cat:"display",gfamily:"Vast+Shadow",weight:"400",tags:["Shadow","Retro","Western"],license:"ofl",year:2012,popular:66},
  {id:"baumans",name:"Baumans",author:"Cyreal",cat:"display",gfamily:"Baumans",weight:"400",tags:["Futuristic","Geometric","Tech"],license:"ofl",year:2012,popular:64},
  {id:"megrim",name:"Megrim",author:"Daniel Johnson",cat:"display",gfamily:"Megrim",weight:"400",tags:["Geometric","Art-Deco","Minimal"],license:"ofl",year:2011,popular:65},
  {id:"fascinate-inline",name:"Fascinate Inline",author:"Astigmatic",cat:"display",gfamily:"Fascinate+Inline",weight:"400",tags:["Retro","Inline","Decorative"],license:"ofl",year:2011,popular:65},
  {id:"black-han-sans",name:"Black Han Sans",author:"Jongsoon Yang",cat:"display",gfamily:"Black+Han+Sans",weight:"400",tags:["Bold","Korean","Strong"],license:"ofl",year:2018,popular:70},
  {id:"changa-one",name:"Changa One",author:"Eduardo Tunni",cat:"display",gfamily:"Changa+One:ital@0;1",weight:"400",tags:["Bold","Condensed","Impact"],license:"ofl",year:2011,popular:74},
  {id:"bree-serif",name:"Bree Serif",author:"TypeTogether",cat:"display",gfamily:"Bree+Serif",weight:"400",tags:["Slab","Friendly","Heading"],license:"ofl",year:2013,popular:76},
  {id:"passion-one",name:"Passion One",author:"Fontstage",cat:"display",gfamily:"Passion+One:wght@400;700;900",weight:"700",tags:["Condensed","Bold","Poster"],license:"ofl",year:2012,popular:73},
  {id:"squada-one",name:"Squada One",author:"Impallari Type",cat:"display",gfamily:"Squada+One",weight:"400",tags:["Geometric","Condensed","Bold"],license:"ofl",year:2013,popular:71},
  {id:"londrina-solid",name:"Londrina Solid",author:"Marcelo Magalhães",cat:"display",gfamily:"Londrina+Solid",weight:"400",tags:["Casual","Handmade","Fun"],license:"ofl",year:2012,popular:72},
  {id:"ultra-condensed",name:"Tilt Neon",author:"Andy Clymer",cat:"display",gfamily:"Tilt+Neon",weight:"400",tags:["Neon","3D","Retro"],license:"ofl",year:2022,popular:68},
  {id:"sarpanch",name:"Sarpanch",author:"Sorkin Type",cat:"display",gfamily:"Sarpanch:wght@400;500;600;700;800;900",weight:"700",tags:["Devanagari","Bold","Poster"],license:"ofl",year:2014,popular:66},
  {id:"racing-sans-one",name:"Racing Sans One",author:"Impallari Type",cat:"display",gfamily:"Racing+Sans+One",weight:"400",tags:["Italic","Speed","Bold"],license:"ofl",year:2013,popular:70},
  {id:"permanent-marker-display",name:"Permanent Marker",author:"Font Diner",cat:"display",gfamily:"Permanent+Marker",weight:"400",tags:["Marker","Casual","Hand"],license:"apache",year:2010,popular:85},
  {id:"lobster",name:"Lobster",author:"Pablo Impallari",cat:"display",gfamily:"Lobster",weight:"400",tags:["Script","Retro","Fun"],license:"ofl",year:2010,popular:91},
  {id:"lobster-two",name:"Lobster Two",author:"Pablo Impallari",cat:"display",gfamily:"Lobster+Two:ital,wght@0,400;0,700;1,400;1,700",weight:"400",tags:["Script","Retro","Italic"],license:"ofl",year:2010,popular:82},
  {id:"alfa-slab-two",name:"Boogaloo",author:"John Vargas Beltrán",cat:"display",gfamily:"Boogaloo",weight:"400",tags:["Retro","Casual","Playful"],license:"ofl",year:2012,popular:75},
  {id:"cherry-bomb",name:"Cherry Bomb One",author:"Fontworks",cat:"display",gfamily:"Cherry+Bomb+One",weight:"400",tags:["Bold","Playful","Japanese"],license:"ofl",year:2022,popular:67},
  {id:"baumans-two",name:"Gugi",author:"Typefaces by Dalton Maag",cat:"display",gfamily:"Gugi",weight:"400",tags:["Korean","Geometric","Bold"],license:"ofl",year:2018,popular:65},
  {id:"dela-gothic-one",name:"Dela Gothic One",author:"Fontworks",cat:"display",gfamily:"Dela+Gothic+One",weight:"400",tags:["Bold","Japanese","Display"],license:"ofl",year:2022,popular:69},
  {id:"fraunces-display",name:"Fraunces",author:"Undercase Type",cat:"display",gfamily:"Fraunces:ital,opsz,wght@0,9..144,300;0,9..144,700;1,9..144,400",weight:"700",tags:["Variable","Optical","Display"],license:"ofl",year:2020,popular:74},
  {id:"anton",name:"Anton",author:"Vernon Adams",cat:"display",gfamily:"Anton",weight:"400",tags:["Impact","Condensed","Poster"],license:"ofl",year:2011,popular:88},
  {id:"rubik-dirt",name:"Rubik Dirt",author:"Philipp Hubert",cat:"display",gfamily:"Rubik+Dirt",weight:"400",tags:["Textured","Bold","Grunge"],license:"ofl",year:2021,popular:66},
  {id:"rubik-moonrocks",name:"Rubik Moonrocks",author:"Philipp Hubert",cat:"display",gfamily:"Rubik+Moonrocks",weight:"400",tags:["Textured","Funky","Bold"],license:"ofl",year:2021,popular:64},
  {id:"fixture",name:"Big Shoulders Display",author:"Patric King",cat:"display",gfamily:"Big+Shoulders+Display:wght@100;300;400;700;900",weight:"700",tags:["Condensed","Display","Bold"],license:"ofl",year:2019,popular:73},
  {id:"climate-crisis",name:"Climate Crisis",author:"FC-fonts",cat:"display",gfamily:"Climate+Crisis",weight:"400",tags:["Variable","Experimental","Protest"],license:"ofl",year:2022,popular:62},
  {id:"rammetto-one",name:"Rammetto One",author:"Cyreal",cat:"display",gfamily:"Rammetto+One",weight:"400",tags:["Rounded","Bold","Fun"],license:"ofl",year:2011,popular:67},
  {id:"righteous-alt",name:"Poller One",author:"Tipo",cat:"display",gfamily:"Poller+One",weight:"400",tags:["Slab","Display","Bold"],license:"ofl",year:2011,popular:65},
  {id:"emblema-one",name:"Emblema One",author:"Gesine Todt",cat:"display",gfamily:"Emblema+One",weight:"400",tags:["Vintage","Ornate","Display"],license:"ofl",year:2012,popular:60},
  {id:"averia-serif-libre",name:"Averia Serif Libre",author:"Dan Sayers",cat:"display",gfamily:"Averia+Serif+Libre:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Average","Unique","Serif"],license:"ofl",year:2012,popular:61},
  {id:"codystar",name:"Codystar",author:"Rainer Scheichelbauer",cat:"display",gfamily:"Codystar:wght@300;400",weight:"400",tags:["Futuristic","Thin","Display"],license:"ofl",year:2013,popular:58},
  {id:"warnes",name:"Warnes",author:"Astigmatic",cat:"display",gfamily:"Warnes",weight:"400",tags:["Circus","Vintage","Fun"],license:"ofl",year:2012,popular:59},
  {id:"butcherman",name:"Butcherman",author:"Astigmatic",cat:"display",gfamily:"Butcherman",weight:"400",tags:["Horror","Western","Decorative"],license:"ofl",year:2012,popular:62},
  {id:"henny-penny",name:"Henny Penny",author:"Brownfox",cat:"display",gfamily:"Henny+Penny",weight:"400",tags:["Whimsical","Fantasy","Display"],license:"ofl",year:2014,popular:63},
  {id:"alice",name:"Alice",author:"Ksenia Erulevich",cat:"serif",gfamily:"Alice",weight:"400",tags:["Elegant","Literary","Classic"],license:"ofl",year:2011,popular:72},
  {id:"cardo",name:"Cardo",author:"David Perry",cat:"serif",gfamily:"Cardo:ital,wght@0,400;0,700;1,400",weight:"400",tags:["Scholarly","Classic","Books"],license:"ofl",year:2011,popular:74},
  {id:"neuton",name:"Neuton",author:"Brian Zick",cat:"serif",gfamily:"Neuton:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Oldstyle","Reading","Literary"],license:"ofl",year:2011,popular:69},
  {id:"fjord-one",name:"Fjord One",author:"Viktoriya Grabowska",cat:"serif",gfamily:"Fjord+One",weight:"400",tags:["Nordic","Elegant","Editorial"],license:"ofl",year:2012,popular:64},
  {id:"gentium-plus",name:"Gentium Plus",author:"SIL International",cat:"serif",gfamily:"Gentium+Plus:ital@0;1",weight:"400",tags:["Multilingual","Scholarly","Reading"],license:"ofl",year:2021,popular:68},
  {id:"noto-serif",name:"Noto Serif",author:"Google",cat:"serif",gfamily:"Noto+Serif:ital,wght@0,400;0,700;1,400",weight:"400",tags:["Universal","Multilingual","Reading"],license:"ofl",year:2012,popular:80},
  {id:"petrona",name:"Petrona",author:"Mariana Saraiva",cat:"serif",gfamily:"Petrona:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Slab","Variable","Editorial"],license:"ofl",year:2012,popular:67},
  {id:"ultra",name:"Ultra",author:"Cyreal",cat:"serif",gfamily:"Ultra",weight:"400",tags:["Bold","Display","Poster"],license:"ofl",year:2011,popular:71},
  {id:"josefin-slab",name:"Josefin Slab",author:"Santiago Orozco",cat:"serif",gfamily:"Josefin+Slab:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Geometric","Slab","Elegant"],license:"ofl",year:2010,popular:75},
  {id:"roboto-slab",name:"Roboto Slab",author:"Christian Robertson",cat:"serif",gfamily:"Roboto+Slab:wght@300;400;700;900",weight:"400",tags:["Slab","Android","Neutral"],license:"apache",year:2013,popular:88},
  {id:"tinos",name:"Tinos",author:"Steve Matteson",cat:"serif",gfamily:"Tinos:ital,wght@0,400;0,700;1,400;1,700",weight:"400",tags:["Metric","Classic","Reading"],license:"apache",year:2010,popular:66},
  {id:"vollkorn",name:"Vollkorn",author:"Friedrich Althausen",cat:"serif",gfamily:"Vollkorn:ital,wght@0,400;0,700;0,900;1,400",weight:"400",tags:["Old-Style","Variable","Books"],license:"ofl",year:2010,popular:73},
  {id:"dm-serif-text",name:"DM Serif Text",author:"Colophon Foundry",cat:"serif",gfamily:"DM+Serif+Text:ital@0;1",weight:"400",tags:["Editorial","Contrast","Text"],license:"ofl",year:2019,popular:76},
  {id:"gfs-didot",name:"GFS Didot",author:"Greek Font Society",cat:"serif",gfamily:"GFS+Didot",weight:"400",tags:["Didone","Greek","Elegant"],license:"ofl",year:2010,popular:63},
  {id:"ibm-plex-serif",name:"IBM Plex Serif",author:"Bold Monday",cat:"serif",gfamily:"IBM+Plex+Serif:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["IBM","Corporate","Reading"],license:"ofl",year:2017,popular:79},
  {id:"instrument-serif",name:"Instrument Serif",author:"Rodrigo Fuenzalida",cat:"serif",gfamily:"Instrument+Serif:ital@0;1",weight:"400",tags:["Editorial","Elegant","Contrast"],license:"ofl",year:2023,popular:78},
  {id:"young-serif",name:"Young Serif",author:"Bastien Sozoo",cat:"serif",gfamily:"Young+Serif",weight:"400",tags:["Transitional","Classic","Reading"],license:"ofl",year:2023,popular:70},
  {id:"rozha-one",name:"Rozha One",author:"Indian Type Foundry",cat:"serif",gfamily:"Rozha+One",weight:"400",tags:["Display","High-Contrast","Bold"],license:"ofl",year:2014,popular:72},
  {id:"libre-caslon-text",name:"Libre Caslon Text",author:"Impallari Type",cat:"serif",gfamily:"Libre+Caslon+Text:ital,wght@0,400;0,700;1,400",weight:"400",tags:["Caslon","Classic","Books"],license:"ofl",year:2012,popular:74},
  {id:"charis-sil",name:"Charis SIL",author:"SIL International",cat:"serif",gfamily:"Charis+SIL:ital,wght@0,400;0,700;1,400;1,700",weight:"400",tags:["Linguistic","Readable","Academic"],license:"ofl",year:2014,popular:65},
  {id:"gelasio",name:"Gelasio",author:"Eben Sorkin",cat:"serif",gfamily:"Gelasio:ital,wght@0,400;0,500;0,700;1,400",weight:"400",tags:["Garamond","Classic","Text"],license:"ofl",year:2020,popular:67},
  {id:"brygada-1918",name:"Brygada 1918",author:"Mateusz Machalski",cat:"serif",gfamily:"Brygada+1918:ital,wght@0,400;0,700;1,400",weight:"400",tags:["Historical","Polish","Classic"],license:"ofl",year:2021,popular:64},
  {id:"frank-ruhl-libre",name:"Frank Ruhl Libre",author:"Ben Nathan",cat:"serif",gfamily:"Frank+Ruhl+Libre:wght@300;400;500;700;900",weight:"400",tags:["Hebrew","Variable","Elegant"],license:"ofl",year:2015,popular:68},
  {id:"cormorant-infant",name:"Cormorant Infant",author:"Christian Thalmann",cat:"serif",gfamily:"Cormorant+Infant:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Elegant","Garamond","Vintage"],license:"ofl",year:2015,popular:71},
  {id:"headland-one",name:"Headland One",author:"Sorkin Type",cat:"serif",gfamily:"Headland+One",weight:"400",tags:["Display","Transitional","Sharp"],license:"ofl",year:2012,popular:62},
  {id:"fanwood-text",name:"Fanwood Text",author:"Barry Schwartz",cat:"serif",gfamily:"Fanwood+Text:ital@0;1",weight:"400",tags:["Literary","Classic","Books"],license:"ofl",year:2010,popular:61},
  {id:"radio-canada",name:"Radio Canada",author:"Displaay",cat:"serif",gfamily:"Radio+Canada:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Variable","Accessible","Clean"],license:"ofl",year:2022,popular:66},
  {id:"baskervville",name:"Baskervville",author:"Irina Petrova",cat:"serif",gfamily:"Baskervville:ital@0;1",weight:"400",tags:["Baskerville","Classic","Elegant"],license:"ofl",year:2017,popular:72},
  {id:"sora",name:"Sora",author:"Jonathan Barnbrook",cat:"sans-serif",gfamily:"Sora:wght@300;400;600;700;800",weight:"400",tags:["Geometric","Modern","Variable"],license:"ofl",year:2019,popular:74},
  {id:"be-vietnam-pro",name:"Be Vietnam Pro",author:"Be Vietnam Pro",cat:"sans-serif",gfamily:"Be+Vietnam+Pro:ital,wght@0,300;0,400;0,500;0,600;0,700;1,400",weight:"400",tags:["Humanist","Vietnamese","Variable"],license:"ofl",year:2021,popular:72},
  {id:"red-hat-display",name:"Red Hat Display",author:"MCKL",cat:"sans-serif",gfamily:"Red+Hat+Display:ital,wght@0,300;0,400;0,700;0,900;1,400",weight:"400",tags:["Humanist","Variable","Tech"],license:"ofl",year:2019,popular:75},
  {id:"lexend",name:"Lexend",author:"Thomas Jockin",cat:"sans-serif",gfamily:"Lexend:wght@300;400;500;600;700",weight:"400",tags:["Readability","Variable","Clean"],license:"ofl",year:2018,popular:76},
  {id:"space-grotesk",name:"Space Grotesk",author:"Florian Karsten",cat:"sans-serif",gfamily:"Space+Grotesk:wght@300;400;500;600;700",weight:"400",tags:["Quirky","Tech","Modern"],license:"ofl",year:2018,popular:85},
  {id:"epilogue",name:"Epilogue",author:"Tyler Finck",cat:"sans-serif",gfamily:"Epilogue:ital,wght@0,300;0,400;0,700;0,900;1,400",weight:"400",tags:["Grotesque","Variable","Editorial"],license:"ofl",year:2020,popular:71},
  {id:"hanken-grotesk",name:"Hanken Grotesk",author:"Hanken Design Co",cat:"sans-serif",gfamily:"Hanken+Grotesk:ital,wght@0,300;0,400;0,500;0,700;1,400",weight:"400",tags:["Neo-Grotesque","Clean","Variable"],license:"ofl",year:2022,popular:70},
  {id:"geist",name:"Geist",author:"Vercel",cat:"sans-serif",gfamily:"Geist:wght@300;400;500;600;700;800",weight:"400",tags:["Modern","UI","Developer"],license:"ofl",year:2023,popular:73},
  {id:"bricolage-grotesque",name:"Bricolage Grotesque",author:"Mathieu Triay",cat:"sans-serif",gfamily:"Bricolage+Grotesque:opsz,wght@12,300;12,400;12,700;12,800",weight:"400",tags:["Grotesque","Variable","Display"],license:"ofl",year:2023,popular:69},
  {id:"onest",name:"Onest",author:"Onest",cat:"sans-serif",gfamily:"Onest:wght@300;400;500;600;700;800",weight:"400",tags:["Geometric","Clean","Variable"],license:"ofl",year:2022,popular:68},
  {id:"instrument-sans",name:"Instrument Sans",author:"Rodrigo Fuenzalida",cat:"sans-serif",gfamily:"Instrument+Sans:ital,wght@0,400;0,500;0,600;0,700;1,400",weight:"400",tags:["Grotesque","Modern","Variable"],license:"ofl",year:2022,popular:72},
  {id:"public-sans",name:"Public Sans",author:"USWDS",cat:"sans-serif",gfamily:"Public+Sans:ital,wght@0,300;0,400;0,700;0,900;1,400",weight:"400",tags:["Government","Neutral","Variable"],license:"ofl",year:2019,popular:67},
  {id:"inter-tight",name:"Inter Tight",author:"Rasmus Andersson",cat:"sans-serif",gfamily:"Inter+Tight:ital,wght@0,300;0,400;0,500;0,700;1,400",weight:"400",tags:["Condensed","UI","Variable"],license:"ofl",year:2022,popular:71},
  {id:"archivo",name:"Archivo",author:"Omnibus-Type",cat:"sans-serif",gfamily:"Archivo:ital,wght@0,300;0,400;0,500;0,700;1,400",weight:"400",tags:["Grotesque","Variable","Versatile"],license:"ofl",year:2016,popular:74},
  {id:"gothic-a1",name:"Gothic A1",author:"Bohyeon Moon",cat:"sans-serif",gfamily:"Gothic+A1:wght@300;400;500;700;900",weight:"400",tags:["Korean","Clean","Variable"],license:"ofl",year:2018,popular:66},
  {id:"geologica",name:"Geologica",author:"Monokrom",cat:"sans-serif",gfamily:"Geologica:slnt,wght@-12,100;0,300;0,400;0,700",weight:"400",tags:["Variable","Grotesque","Modern"],license:"ofl",year:2023,popular:68},
  {id:"lexend-deca",name:"Lexend Deca",author:"Thomas Jockin",cat:"sans-serif",gfamily:"Lexend+Deca:wght@300;400;500;700",weight:"400",tags:["Readability","Variable","Clean"],license:"ofl",year:2019,popular:73},
  {id:"gantari",name:"Gantari",author:"Google Design",cat:"sans-serif",gfamily:"Gantari:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Humanist","Variable","UI"],license:"ofl",year:2022,popular:64},
  {id:"chakra-petch",name:"Chakra Petch",author:"Cadson Demak",cat:"sans-serif",gfamily:"Chakra+Petch:ital,wght@0,300;0,400;0,600;1,400",weight:"400",tags:["Tech","Condensed","Thai"],license:"ofl",year:2020,popular:71},
  {id:"mohave",name:"Mohave",author:"Kimberley Geswein",cat:"sans-serif",gfamily:"Mohave:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Condensed","Geometric","Display"],license:"ofl",year:2020,popular:67},
  {id:"heebo",name:"Heebo",author:"Oded Ezer",cat:"sans-serif",gfamily:"Heebo:wght@300;400;500;700;900",weight:"400",tags:["Hebrew","Variable","Clean"],license:"ofl",year:2014,popular:82},
  {id:"saira",name:"Saira",author:"Omnibus-Type",cat:"sans-serif",gfamily:"Saira:ital,wght@0,300;0,400;0,700;0,900;1,400",weight:"400",tags:["Variable","Condensed","Grotesque"],license:"ofl",year:2016,popular:68},
  {id:"kosugi-maru",name:"Kosugi Maru",author:"Motoya",cat:"sans-serif",gfamily:"Kosugi+Maru",weight:"400",tags:["Japanese","Rounded","Clean"],license:"apache",year:2018,popular:63},
  {id:"proza-libre",name:"Proza Libre",author:"Bureau Roffa",cat:"sans-serif",gfamily:"Proza+Libre:ital,wght@0,400;0,500;0,700;1,400",weight:"400",tags:["Humanist","Text","Versatile"],license:"ofl",year:2016,popular:66},
  {id:"overpass",name:"Overpass",author:"Delve Fonts",cat:"sans-serif",gfamily:"Overpass:ital,wght@0,300;0,400;0,700;0,900;1,400",weight:"400",tags:["Highway","Variable","Clean"],license:"ofl",year:2016,popular:69},
  {id:"varta",name:"Varta",author:"Jonny Pinhorn",cat:"sans-serif",gfamily:"Varta:wght@300;400;500;600;700",weight:"400",tags:["Variable","Clean","Reading"],license:"ofl",year:2019,popular:64},
  {id:"encode-sans-condensed",name:"Encode Sans Condensed",author:"Impallari Type",cat:"sans-serif",gfamily:"Encode+Sans+Condensed:wght@300;400;600;700;900",weight:"400",tags:["Condensed","Variable","Neutral"],license:"ofl",year:2015,popular:67},
  {id:"arimo",name:"Arimo",author:"Steve Matteson",cat:"sans-serif",gfamily:"Arimo:ital,wght@0,400;0,500;0,700;1,400",weight:"400",tags:["Metric","Screen","Variable"],license:"apache",year:2010,popular:72},
  {id:"nunito-sans",name:"Nunito Sans",author:"Vernon Adams",cat:"sans-serif",gfamily:"Nunito+Sans:ital,opsz,wght@0,6..12,300;0,6..12,400;0,6..12,700;1,6..12,400",weight:"400",tags:["Rounded","Variable","Friendly"],license:"ofl",year:2014,popular:84},
  {id:"kantumruy-pro",name:"Kantumruy Pro",author:"Tep Sovichet",cat:"sans-serif",gfamily:"Kantumruy+Pro:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Khmer","Variable","Clean"],license:"ofl",year:2022,popular:60},
  {id:"asap",name:"Asap",author:"Omnibus-Type",cat:"sans-serif",gfamily:"Asap:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Humanist","Variable","Text"],license:"ofl",year:2012,popular:70},
  {id:"hind",name:"Hind",author:"Indian Type Foundry",cat:"sans-serif",gfamily:"Hind:wght@300;400;500;600;700",weight:"400",tags:["Devanagari","Text","Neutral"],license:"ofl",year:2014,popular:75},
  {id:"almendra",name:"Almendra",author:"Ana Sanfelippo",cat:"monospace",gfamily:"Almendra:ital,wght@0,400;0,700;1,400",weight:"400",tags:["Fantasy","Medieval","Decorative"],license:"ofl",year:2012,popular:65},
  {id:"mystery-quest",name:"Mystery Quest",author:"Astigmatic",cat:"monospace",gfamily:"Mystery+Quest",weight:"400",tags:["Decorative","Fantasy","Retro"],license:"ofl",year:2012,popular:60},
  {id:"caesar-dressing",name:"Caesar Dressing",author:"Astigmatic",cat:"monospace",gfamily:"Caesar+Dressing",weight:"400",tags:["Decorative","Roman","Ornate"],license:"ofl",year:2012,popular:58},
  {id:"underdog",name:"Underdog",author:"Jovanny Lemonad",cat:"monospace",gfamily:"Underdog",weight:"400",tags:["Playful","Casual","Retro"],license:"ofl",year:2012,popular:57},
  {id:"rye",name:"Rye",author:"Astigmatic",cat:"monospace",gfamily:"Rye",weight:"400",tags:["Western","Vintage","Display"],license:"ofl",year:2012,popular:63},
  {id:"eater",name:"Eater",author:"Typomondo",cat:"monospace",gfamily:"Eater",weight:"400",tags:["Horror","Halloween","Decorative"],license:"ofl",year:2012,popular:62},
  {id:"lacquer",name:"Lacquer",author:"Eli Block",cat:"monospace",gfamily:"Lacquer",weight:"400",tags:["Grunge","Ink","Textured"],license:"ofl",year:2016,popular:61},
  {id:"metal-mania",name:"Metal Mania",author:"Astigmatic",cat:"monospace",gfamily:"Metal+Mania",weight:"400",tags:["Metal","Rock","Decorative"],license:"ofl",year:2012,popular:60},
  {id:"kumar-one",name:"Kumar One",author:"Jonny Pinhorn",cat:"monospace",gfamily:"Kumar+One",weight:"400",tags:["Gujarati","Bold","Display"],license:"ofl",year:2016,popular:59},
  {id:"sofia",name:"Sofia",author:"Latinotype",cat:"monospace",gfamily:"Sofia",weight:"400",tags:["Script","Decorative","Elegant"],license:"ofl",year:2012,popular:64},
  {id:"diplomata-sc",name:"Diplomata SC",author:"Latinotype",cat:"monospace",gfamily:"Diplomata+SC",weight:"400",tags:["Decorative","Small-Caps","Ornate"],license:"ofl",year:2012,popular:58},
  {id:"rum-raisin",name:"Rum Raisin",author:"Astigmatic",cat:"monospace",gfamily:"Rum+Raisin",weight:"400",tags:["Retro","Vintage","Bold"],license:"ofl",year:2012,popular:60},
  {id:"puppies-play",name:"Puppies Play",author:"Khurasan",cat:"monospace",gfamily:"Puppies+Play",weight:"400",tags:["Playful","Cute","Fun"],license:"ofl",year:2021,popular:56},
  {id:"stalinist-one",name:"Stalinist One",author:"Jovanny Lemonad",cat:"monospace",gfamily:"Stalinist+One",weight:"400",tags:["Soviet","Bold","Decorative"],license:"ofl",year:2012,popular:61},
  {id:"bungee-shade",name:"Bungee Shade",author:"David Jonathan Ross",cat:"display",gfamily:"Bungee+Shade",weight:"400",tags:["Shadow","Urban","3D"],license:"ofl",year:2015,popular:72},
  {id:"bungee-inline",name:"Bungee Inline",author:"David Jonathan Ross",cat:"display",gfamily:"Bungee+Inline",weight:"400",tags:["Inline","Urban","Poster"],license:"ofl",year:2015,popular:70},
  {id:"sigmar",name:"Sigmar",author:"Yanone Kaffeesatz",cat:"display",gfamily:"Sigmar",weight:"400",tags:["Bold","Slab","Display"],license:"ofl",year:2022,popular:65},
  {id:"pixelify-sans",name:"Pixelify Sans",author:"Stefie Justprince",cat:"display",gfamily:"Pixelify+Sans:wght@400;500;600;700",weight:"700",tags:["Pixel","Retro","Gaming"],license:"ofl",year:2023,popular:71},
  {id:"host-grotesk",name:"Host Grotesk",author:"Host",cat:"display",gfamily:"Host+Grotesk:ital,wght@0,300;0,400;0,500;0,700;1,400",weight:"400",tags:["Grotesque","Modern","Clean"],license:"ofl",year:2023,popular:66},
  {id:"jacquard-24",name:"Jacquard 24",author:"Alphabet Type",cat:"display",gfamily:"Jacquard+24",weight:"400",tags:["Pixel","Bitmap","Retro"],license:"ofl",year:2023,popular:64},
  {id:"silkscreen-bold",name:"Nabla",author:"Arthur Reinders Folmer",cat:"display",gfamily:"Nabla",weight:"400",tags:["Color","Variable","3D"],license:"ofl",year:2022,popular:67},
  {id:"meow-script",name:"Meow Script",author:"Robert Leuschke",cat:"display",gfamily:"Meow+Script",weight:"400",tags:["Script","Ligatures","Calligraphy"],license:"ofl",year:2021,popular:63},
  {id:"rubik-glitch",name:"Rubik Glitch",author:"Philipp Hubert",cat:"display",gfamily:"Rubik+Glitch",weight:"400",tags:["Glitch","Experimental","Digital"],license:"ofl",year:2021,popular:66},
  {id:"honk",name:"Honk",author:"David Jonathan Ross",cat:"display",gfamily:"Honk",weight:"400",tags:["Color","Variable","Funky"],license:"ofl",year:2023,popular:62},
  {id:"red-hat-mono",name:"Red Hat Mono",author:"MCKL",cat:"monospace",gfamily:"Red+Hat+Mono:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Code","Variable","Tech"],license:"ofl",year:2020,popular:72},
  {id:"azeret-mono",name:"Azeret Mono",author:"Degarism Studio",cat:"monospace",gfamily:"Azeret+Mono:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Monospace","Variable","Modern"],license:"ofl",year:2021,popular:68},
  {id:"martian-mono",name:"Martian Mono",author:"Roman Shamin",cat:"monospace",gfamily:"Martian+Mono:wght@300;400;600;800",weight:"400",tags:["Code","Variable","Sci-Fi"],license:"ofl",year:2022,popular:70},
  {id:"noto-sans-mono",name:"Noto Sans Mono",author:"Google",cat:"monospace",gfamily:"Noto+Sans+Mono:wght@300;400;700;900",weight:"400",tags:["Unicode","Variable","Neutral"],license:"ofl",year:2016,popular:75},
  {id:"lekton",name:"Lekton",author:"Accademia di Belle Arti di Urbino",cat:"monospace",gfamily:"Lekton:ital,wght@0,400;0,700;1,400",weight:"400",tags:["Monospace","Minimal","Code"],license:"ofl",year:2012,popular:65},
  {id:"syne-mono",name:"Syne Mono",author:"Bonjour Monde",cat:"monospace",gfamily:"Syne+Mono",weight:"400",tags:["Experimental","Monospace","Modern"],license:"ofl",year:2019,popular:67},
  {id:"nova-mono",name:"Nova Mono",author:"Wojciech Kalinowski",cat:"monospace",gfamily:"Nova+Mono",weight:"400",tags:["Futuristic","Monospace","Sci-Fi"],license:"ofl",year:2011,popular:63},
  {id:"cutive-mono",name:"Cutive Mono",author:"Vernon Adams",cat:"monospace",gfamily:"Cutive+Mono",weight:"400",tags:["Typewriter","Mono","Vintage"],license:"ofl",year:2012,popular:72},
  {id:"xanh-mono",name:"Xanh Mono",author:"Phan Thanh Vinh",cat:"monospace",gfamily:"Xanh+Mono:ital@0;1",weight:"400",tags:["Vietnamese","Monospace","Minimal"],license:"ofl",year:2020,popular:60},
  {id:"major-mono-display",name:"Major Mono Display",author:"Emre Parlak",cat:"monospace",gfamily:"Major+Mono+Display",weight:"400",tags:["Monospace","Display","Geometric"],license:"ofl",year:2019,popular:66},
  {id:"b612-mono",name:"B612 Mono",author:"Airbus",cat:"monospace",gfamily:"B612+Mono:ital,wght@0,400;0,700;1,400",weight:"400",tags:["Aviation","Monospace","Legible"],license:"ofl",year:2018,popular:64},
  {id:"ubuntu-mono",name:"Ubuntu Mono",author:"Dalton Maag",cat:"monospace",gfamily:"Ubuntu+Mono:ital,wght@0,400;0,700;1,400",weight:"400",tags:["Ubuntu","Monospace","Linux"],license:"ufl",year:2010,popular:79},
  {id:"geist-mono",name:"Geist Mono",author:"Vercel",cat:"monospace",gfamily:"Geist+Mono:wght@300;400;500;700",weight:"400",tags:["Code","Variable","Modern"],license:"ofl",year:2023,popular:76},
  {id:"departure-mono",name:"Departure Mono",author:"Helena Zhang",cat:"monospace",gfamily:"Departure+Mono",weight:"400",tags:["Pixel","Terminal","Retro"],license:"ofl",year:2024,popular:67},
  {id:"monaspace-neon",name:"Monaspace Neon",author:"GitHub",cat:"monospace",gfamily:"Monaspace+Neon:wght@300;400;700",weight:"400",tags:["Code","Variable","GitHub"],license:"ofl",year:2023,popular:70},
  {id:"lilex",name:"Lilex",author:"mishamyrt",cat:"monospace",gfamily:"Lilex:wght@300;400;700",weight:"400",tags:["Code","Ligatures","Variable"],license:"ofl",year:2020,popular:62},
  {id:"recursive",name:"Recursive",author:"Arrow Type",cat:"monospace",gfamily:"Recursive:slnt,wght@0,300;0,400;0,700;-15,400",weight:"400",tags:["Variable","Monospace","Expressive"],license:"ofl",year:2020,popular:73},
  {id:"texturina",name:"Texturina",author:"Omnibus-Type",cat:"other",gfamily:"Texturina:ital,opsz,wght@0,12,300;0,12,400;0,12,700;1,12,400",weight:"400",tags:["Blackletter","Variable","Medieval"],license:"ofl",year:2020,popular:64},
  {id:"unifraktur-maguntia",name:"UnifrakturMaguntia",author:"j. 'mach' wust",cat:"other",gfamily:"UnifrakturMaguntia",weight:"400",tags:["Blackletter","Gothic","Medieval"],license:"ofl",year:2011,popular:68},
  {id:"old-standard-tt",name:"Old Standard TT",author:"Alexei Vanyashin",cat:"other",gfamily:"Old+Standard+TT:ital,wght@0,400;0,700;1,400",weight:"400",tags:["Academic","Classic","Scholarly"],license:"ofl",year:2010,popular:72},
  {id:"astloch",name:"Astloch",author:"Anke-Art",cat:"other",gfamily:"Astloch:wght@400;700",weight:"400",tags:["Blackletter","Decorative","Gothic"],license:"ofl",year:2011,popular:60},
  {id:"im-fell-english",name:"IM Fell English",author:"Igino Marini",cat:"other",gfamily:"IM+Fell+English:ital@0;1",weight:"400",tags:["Historical","Italic","Vintage"],license:"ofl",year:2010,popular:71},
  {id:"pirata-one",name:"Pirata One",author:"Integrated Script",cat:"other",gfamily:"Pirata+One",weight:"400",tags:["Blackletter","Pirate","Decorative"],license:"ofl",year:2012,popular:66},
  {id:"medieval-sharp",name:"MedievalSharp",author:"Peter Wiegel",cat:"other",gfamily:"MedievalSharp",weight:"400",tags:["Medieval","Gothic","Sharp"],license:"ofl",year:2011,popular:62},
  {id:"sevillana",name:"Sevillana",author:"Rodrigo Fuenzalida",cat:"other",gfamily:"Sevillana",weight:"400",tags:["Ornamental","Decorative","Spanish"],license:"ofl",year:2012,popular:63},
  {id:"kumar-one-outline",name:"Kumar One Outline",author:"Indian Type Foundry",cat:"other",gfamily:"Kumar+One+Outline",weight:"400",tags:["Outline","Gujarati","Display"],license:"ofl",year:2017,popular:61},
  {id:"fruktur",name:"Fruktur",author:"Alexei Vanyashin",cat:"other",gfamily:"Fruktur:ital@0;1",weight:"400",tags:["Blackletter","Cyrillic","Gothic"],license:"ofl",year:2012,popular:59},
  {id:"trade-winds",name:"Trade Winds",author:"Astigmatic",cat:"other",gfamily:"Trade+Winds",weight:"400",tags:["Nautical","Vintage","Display"],license:"apache",year:2010,popular:65},
  {id:"kranky",name:"Kranky",author:"Font Diner",cat:"other",gfamily:"Kranky",weight:"400",tags:["Grunge","Horror","Rough"],license:"apache",year:2010,popular:61},
  {id:"smokum",name:"Smokum",author:"Astigmatic",cat:"other",gfamily:"Smokum",weight:"400",tags:["Western","Vintage","Display"],license:"apache",year:2010,popular:59},
  {id:"windSong",name:"WindSong",author:"Piotr Wozniak",cat:"other",gfamily:"WindSong:wght@400;500",weight:"400",tags:["Calligraphy","Elegant","Script"],license:"ofl",year:2021,popular:66},
  {id:"ingrid-darling",name:"Ingrid Darling",author:"Robert Leuschke",cat:"other",gfamily:"Ingrid+Darling",weight:"400",tags:["Script","Elegant","Wedding"],license:"ofl",year:2021,popular:65},
  {id:"port-lligat-slab",name:"Port Lligat Slab",author:"Tipo Pèpel",cat:"other",gfamily:"Port+Lligat+Slab",weight:"400",tags:["Slab","Decorative","Vintage"],license:"ofl",year:2012,popular:58},
  {id:"ceviche-one",name:"Ceviche One",author:"Ceviche",cat:"other",gfamily:"Ceviche+One",weight:"400",tags:["Display","Stencil","Bold"],license:"ofl",year:2012,popular:62},
  {id:"noto-serif-ethiopic",name:"Noto Serif Ethiopic",author:"Google",cat:"other",gfamily:"Noto+Serif+Ethiopic:wght@300;400;700;900",weight:"400",tags:["Ethiopic","Variable","Multilingual"],license:"ofl",year:2016,popular:58},
  {id:"noto-nastaliq-urdu",name:"Noto Nastaliq Urdu",author:"Google",cat:"other",gfamily:"Noto+Nastaliq+Urdu:wght@400;700",weight:"400",tags:["Urdu","Arabic","Nastaliq"],license:"ofl",year:2016,popular:61},
  {id:"moulpali",name:"Moulpali",author:"Muthu Nedumaran",cat:"other",gfamily:"Moulpali",weight:"400",tags:["Tamil","Script","Traditional"],license:"ofl",year:2012,popular:57},
  {id:"bungee-hairline",name:"Bungee Hairline",author:"David Jonathan Ross",cat:"other",gfamily:"Bungee+Hairline",weight:"400",tags:["Urban","Thin","Display"],license:"ofl",year:2015,popular:64},
  {id:"rubik-wet-paint",name:"Rubik Wet Paint",author:"Philipp Hubert",cat:"other",gfamily:"Rubik+Wet+Paint",weight:"400",tags:["Dripping","Textured","Horror"],license:"ofl",year:2021,popular:63},
  {id:"rubik-burned",name:"Rubik Burned",author:"Philipp Hubert",cat:"other",gfamily:"Rubik+Burned",weight:"400",tags:["Textured","Grunge","Burned"],license:"ofl",year:2021,popular:61},
  {id:"rubik-vinyl",name:"Rubik Vinyl",author:"Philipp Hubert",cat:"other",gfamily:"Rubik+Vinyl",weight:"400",tags:["Retro","Vinyl","Textured"],license:"ofl",year:2022,popular:60},
  {id:"protest-guerrilla",name:"Protest Guerrilla",author:"Santiago Orozco",cat:"other",gfamily:"Protest+Guerrilla",weight:"400",tags:["Stencil","Street","Bold"],license:"ofl",year:2023,popular:65},
  {id:"protest-riot",name:"Protest Riot",author:"Santiago Orozco",cat:"other",gfamily:"Protest+Riot",weight:"400",tags:["Bold","Street","Protest"],license:"ofl",year:2023,popular:63},
  {id:"protest-revolution",name:"Protest Revolution",author:"Santiago Orozco",cat:"other",gfamily:"Protest+Revolution",weight:"400",tags:["Display","Bold","Statement"],license:"ofl",year:2023,popular:62},
  {id:"simonetta",name:"Simonetta",author:"Astigmatic",cat:"other",gfamily:"Simonetta:ital,wght@0,400;0,900;1,400",weight:"400",tags:["Vintage","Ornate","Italic"],license:"ofl",year:2012,popular:61},
  {id:"inknut-antiqua",name:"Inknut Antiqua",author:"Clougher Corporation",cat:"other",gfamily:"Inknut+Antiqua:wght@300;400;600;700;800;900",weight:"400",tags:["Devanagari","Antiqua","Display"],license:"ofl",year:2016,popular:67},
  {id:"palette-mosaic",name:"Palette Mosaic",author:"Tetsuya Ohara",cat:"other",gfamily:"Palette+Mosaic",weight:"400",tags:["Color","Japanese","Decorative"],license:"ofl",year:2022,popular:60},
  {id:"oi",name:"Oi",author:"Eduardo Tunni",cat:"other",gfamily:"Oi",weight:"400",tags:["Victorian","Ornate","Display"],license:"ofl",year:2013,popular:61},
  {id:"boogaloo-extra",name:"Federant",author:"Astigmatic",cat:"other",gfamily:"Federant",weight:"400",tags:["Art Nouveau","Ornate","Vintage"],license:"apache",year:2010,popular:59},
  {id:"zen-tokyo-zoo",name:"Zen Tokyo Zoo",author:"Yoshimichi Ohira",cat:"other",gfamily:"Zen+Tokyo+Zoo",weight:"400",tags:["Japanese","Decorative","Bold"],license:"ofl",year:2021,popular:62},
  {id:"cabin",name:"Cabin",author:"Impallari Type",cat:"sans-serif",gfamily:"Cabin:ital,wght@0,400;0,500;0,600;0,700;1,400",weight:"400",tags:["Humanist","Warm","Variable"],license:"ofl",year:2010,popular:80},
  {id:"dosis",name:"Dosis",author:"Edgar Tolentino",cat:"sans-serif",gfamily:"Dosis:wght@300;400;500;600;700;800",weight:"400",tags:["Rounded","Variable","Friendly"],license:"ofl",year:2011,popular:78},
  {id:"noto-sans-jp",name:"Noto Sans JP",author:"Google",cat:"sans-serif",gfamily:"Noto+Sans+JP:wght@300;400;700",weight:"400",tags:["Japanese","Multilingual","System"],license:"ofl",year:2014,popular:82},
  {id:"oxygen",name:"Oxygen",author:"Vernon Adams",cat:"sans-serif",gfamily:"Oxygen:wght@300;400;700",weight:"400",tags:["Clean","UI","KDE"],license:"ofl",year:2012,popular:76},
  {id:"source-sans-3",name:"Source Sans 3",author:"Paul D. Hunt",cat:"sans-serif",gfamily:"Source+Sans+3:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Adobe","Variable","Clean"],license:"ofl",year:2021,popular:78},
  {id:"titillium-web",name:"Titillium Web",author:"Accademia di Belle Arti di Urbino",cat:"sans-serif",gfamily:"Titillium+Web:ital,wght@0,300;0,400;0,600;0,700;1,400",weight:"400",tags:["Condensed","Tech","Formal"],license:"ofl",year:2012,popular:84},
  {id:"exo",name:"Exo",author:"Natanael Gama",cat:"sans-serif",gfamily:"Exo:ital,wght@0,300;0,400;0,600;0,700;1,400",weight:"400",tags:["Geometric","Variable","Tech"],license:"ofl",year:2012,popular:79},
  {id:"pt-sans",name:"PT Sans",author:"ParaType",cat:"sans-serif",gfamily:"PT+Sans:ital,wght@0,400;0,700;1,400",weight:"400",tags:["Humanist","Cyrillic","Universal"],license:"ofl",year:2009,popular:83},
  {id:"jost",name:"Jost",author:"Owen Earl",cat:"sans-serif",gfamily:"Jost:ital,wght@0,300;0,400;0,500;0,700;1,400",weight:"400",tags:["Geometric","Variable","Futura-like"],license:"ofl",year:2019,popular:77},
  {id:"asap",name:"Asap",author:"Omnibus-Type",cat:"sans-serif",gfamily:"Asap:ital,wght@0,300;0,400;0,500;0,700;1,400",weight:"400",tags:["Grotesque","Compact","Variable"],license:"ofl",year:2012,popular:74},
  {id:"arimo",name:"Arimo",author:"Steve Matteson",cat:"sans-serif",gfamily:"Arimo:ital,wght@0,400;0,700;1,400",weight:"400",tags:["Arial","Metrically-compatible","Clean"],license:"apache",year:2010,popular:72},
  {id:"nunito-sans",name:"Nunito Sans",author:"Jacques Le Bailly",cat:"sans-serif",gfamily:"Nunito+Sans:ital,opsz,wght@0,6,300;0,6,400;0,6,700;1,6,400",weight:"400",tags:["Rounded","Variable","Friendly"],license:"ofl",year:2018,popular:81},
  {id:"gfs-didot",name:"GFS Didot",author:"Greek Font Society",cat:"serif",gfamily:"GFS+Didot",weight:"400",tags:["Greek","Didone","Elegant"],license:"ofl",year:2010,popular:68},
  {id:"noto-serif-display",name:"Noto Serif Display",author:"Google",cat:"serif",gfamily:"Noto+Serif+Display:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Universal","Display","Variable"],license:"ofl",year:2016,popular:70},
  {id:"roboto-slab",name:"Roboto Slab",author:"Christian Robertson",cat:"serif",gfamily:"Roboto+Slab:wght@300;400;700;900",weight:"400",tags:["Slab","Android","Versatile"],license:"apache",year:2013,popular:87},
  {id:"vollkorn",name:"Vollkorn",author:"Friedrich Althausen",cat:"serif",gfamily:"Vollkorn:ital,wght@0,400;0,700;1,400",weight:"400",tags:["Literary","Variable","Books"],license:"ofl",year:2010,popular:75},
  {id:"catamaran",name:"Catamaran",author:"Pria Ravichandran",cat:"serif",gfamily:"Catamaran:wght@300;400;600;700;800",weight:"400",tags:["Tamil","Variable","Reading"],license:"ofl",year:2015,popular:69},
  {id:"petrona",name:"Petrona",author:"Veronika Burian",cat:"serif",gfamily:"Petrona:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Variable","Reading","Serif"],license:"ofl",year:2012,popular:67},
  {id:"fenix",name:"Fenix",author:"Botio Nikoltchev",cat:"serif",gfamily:"Fenix",weight:"400",tags:["Transitional","Elegant","Reading"],license:"ofl",year:2012,popular:66},
  {id:"neuton",name:"Neuton",author:"Brian Zick",cat:"serif",gfamily:"Neuton:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Elegant","Variable","Literary"],license:"ofl",year:2011,popular:69},
  {id:"gentium-plus",name:"Gentium Plus",author:"SIL International",cat:"serif",gfamily:"Gentium+Plus:ital,wght@0,400;0,700;1,400",weight:"400",tags:["Multilingual","Scholarly","Classic"],license:"ofl",year:2010,popular:68},
  {id:"charis-sil",name:"Charis SIL",author:"SIL International",cat:"serif",gfamily:"Charis+SIL:ital,wght@0,400;0,700;1,400",weight:"400",tags:["Multilingual","Academic","Humanist"],license:"ofl",year:2010,popular:64},
  {id:"ultra",name:"Ultra",author:"Astigmatic",cat:"display",gfamily:"Ultra",weight:"400",tags:["Heavy","Bold","Poster"],license:"apache",year:2010,popular:70},
  {id:"patua-one",name:"Patua One",author:"Latinotype",cat:"display",gfamily:"Patua+One",weight:"400",tags:["Bold","Poster","Latin"],license:"ofl",year:2010,popular:71},
  {id:"changa",name:"Changa",author:"Eduardo Tunni",cat:"display",gfamily:"Changa:wght@300;400;500;600;700;800",weight:"700",tags:["Arabic","Variable","Bold"],license:"ofl",year:2013,popular:68},
  {id:"rajdhani",name:"Rajdhani",author:"Indian Type Foundry",cat:"display",gfamily:"Rajdhani:wght@300;400;500;600;700",weight:"600",tags:["Devanagari","Condensed","Tech"],license:"ofl",year:2014,popular:76},
  {id:"saira-stencil-one",name:"Saira Stencil One",author:"Omnibus-Type",cat:"display",gfamily:"Saira+Stencil+One",weight:"400",tags:["Stencil","Bold","Military"],license:"ofl",year:2016,popular:65},
  {id:"passion-one",name:"Passion One",author:"Fontstage",cat:"display",gfamily:"Passion+One:wght@400;700;900",weight:"700",tags:["Bold","Heading","Condensed"],license:"ofl",year:2011,popular:73},
  {id:"squada-one",name:"Squada One",author:"Cyreal",cat:"display",gfamily:"Squada+One",weight:"400",tags:["Condensed","Geometric","Tech"],license:"ofl",year:2013,popular:71},
  {id:"rammetto-one",name:"Rammetto One",author:"Cyreal",cat:"display",gfamily:"Rammetto+One",weight:"400",tags:["Rounded","Bold","Comic"],license:"ofl",year:2012,popular:65},
  {id:"racing-sans-one",name:"Racing Sans One",author:"Impallari Type",cat:"display",gfamily:"Racing+Sans+One",weight:"400",tags:["Condensed","Sporty","Italic"],license:"ofl",year:2013,popular:68},
  {id:"modak",name:"Modak",author:"Ek Type",cat:"display",gfamily:"Modak",weight:"400",tags:["Devanagari","Rounded","Bold"],license:"ofl",year:2015,popular:66},
  {id:"tangerine",name:"Tangerine",author:"Toshi Omagari",cat:"handwriting",gfamily:"Tangerine:wght@400;700",weight:"400",tags:["Calligraphy","Thin","Formal"],license:"ofl",year:2010,popular:78},
  {id:"cookie",name:"Cookie",author:"Ania Kruk",cat:"handwriting",gfamily:"Cookie",weight:"400",tags:["Script","Casual","Sweet"],license:"apache",year:2011,popular:74},
  {id:"yellowtail",name:"Yellowtail",author:"Astigmatic",cat:"handwriting",gfamily:"Yellowtail",weight:"400",tags:["Retro","Script","Fun"],license:"apache",year:2011,popular:75},
  {id:"shadows-into-light",name:"Shadows Into Light",author:"Kimberly Geswein",cat:"handwriting",gfamily:"Shadows+Into+Light",weight:"400",tags:["Handwritten","Casual","Natural"],license:"ofl",year:2010,popular:76},
  {id:"amatic-sc",name:"Amatic SC",author:"Vernon Adams",cat:"handwriting",gfamily:"Amatic+SC:wght@400;700",weight:"400",tags:["Condensed","Handwritten","Casual"],license:"ofl",year:2012,popular:80},
  {id:"handlee",name:"Handlee",author:"Joe Prince",cat:"handwriting",gfamily:"Handlee",weight:"400",tags:["Casual","Natural","Print"],license:"ofl",year:2012,popular:67},
  {id:"neucha",name:"Neucha",author:"Jovanny Lemonad",cat:"handwriting",gfamily:"Neucha",weight:"400",tags:["Cyrillic","Handwritten","Casual"],license:"ofl",year:2011,popular:69},
  {id:"nothing-you-could-do",name:"Nothing You Could Do",author:"Kimberly Geswein",cat:"handwriting",gfamily:"Nothing+You+Could+Do",weight:"400",tags:["Casual","Natural","Handwritten"],license:"apache",year:2010,popular:68},
  {id:"zeyada",name:"Zeyada",author:"TypeSETit",cat:"handwriting",gfamily:"Zeyada",weight:"400",tags:["Script","Casual","Flowing"],license:"apache",year:2012,popular:65},
  {id:"liu-jian-mao-cao",name:"Liu Jian Mao Cao",author:"Liu Jian",cat:"handwriting",gfamily:"Liu+Jian+Mao+Cao",weight:"400",tags:["Chinese","Brush","Calligraphy"],license:"ofl",year:2019,popular:63},
  {id:"nanum-gothic-coding",name:"Nanum Gothic Coding",author:"Sandoll",cat:"monospace",gfamily:"Nanum+Gothic+Coding:wght@400;700",weight:"400",tags:["Korean","Code","Terminal"],license:"ofl",year:2012,popular:71},
  {id:"cutive-mono",name:"Cutive Mono",author:"Vernon Adams",cat:"monospace",gfamily:"Cutive+Mono",weight:"400",tags:["Typewriter","Classic","Vintage"],license:"ofl",year:2012,popular:68},
  {id:"overpass-mono",name:"Overpass Mono",author:"Delve Fonts",cat:"monospace",gfamily:"Overpass+Mono:wght@300;400;600;700",weight:"400",tags:["Code","Variable","Clean"],license:"ofl",year:2016,popular:67},
  {id:"pt-mono",name:"PT Mono",author:"ParaType",cat:"monospace",gfamily:"PT+Mono",weight:"400",tags:["Cyrillic","Classic","Terminal"],license:"ofl",year:2010,popular:72},
  {id:"almendra-display",name:"Almendra Display",author:"Ana Sanfelippo",cat:"other",gfamily:"Almendra+Display",weight:"400",tags:["Display","Ornate","Decorative"],license:"ofl",year:2012,popular:63},
  {id:"londrina-solid",name:"Londrina Solid",author:"Marcelo Magalhães",cat:"other",gfamily:"Londrina+Solid",weight:"400",tags:["Brazilian","Display","Bold"],license:"ofl",year:2013,popular:72},
  {id:"caesar-dressing",name:"Caesar Dressing",author:"Astigmatic",cat:"other",gfamily:"Caesar+Dressing",weight:"400",tags:["Decorative","Roman","Display"],license:"apache",year:2011,popular:60},
  {id:"eater",name:"Eater",author:"Typomancer",cat:"other",gfamily:"Eater",weight:"400",tags:["Horror","Dripping","Halloween"],license:"apache",year:2012,popular:61},
  // sans-serif
  {id:"lexend",name:"Lexend",author:"Bonny Fonts",cat:"sans-serif",gfamily:"Lexend:wght@300;400;500;600;700",weight:"400",tags:["Reading","Dyslexia","Variable"],license:"ofl",year:2019,popular:79},
  {id:"be-vietnam-pro",name:"Be Vietnam Pro",author:"Be Vietnam Pro",cat:"sans-serif",gfamily:"Be+Vietnam+Pro:wght@300;400;500;600;700",weight:"400",tags:["Vietnamese","Clean","UI"],license:"ofl",year:2021,popular:76},
  {id:"urbanist",name:"Urbanist",author:"Corey Hu",cat:"sans-serif",gfamily:"Urbanist:wght@300;400;500;600;700;800",weight:"400",tags:["Geometric","Modern","Variable"],license:"ofl",year:2021,popular:77},
  {id:"albert-sans",name:"Albert Sans",author:"Andreas Rasmussen",cat:"sans-serif",gfamily:"Albert+Sans:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Grotesque","Clean","Variable"],license:"ofl",year:2022,popular:74},
  {id:"onest",name:"Onest",author:"Onest",cat:"sans-serif",gfamily:"Onest:wght@300;400;500;700",weight:"400",tags:["Humanist","UI","Cyrillic"],license:"ofl",year:2023,popular:72},
  {id:"red-hat-display",name:"Red Hat Display",author:"MCKL",cat:"sans-serif",gfamily:"Red+Hat+Display:ital,wght@0,300;0,400;0,700;1,400",weight:"700",tags:["Tech","Corporate","Variable"],license:"ofl",year:2019,popular:75},
  {id:"epilogue",name:"Epilogue",author:"Ethan Nakache",cat:"sans-serif",gfamily:"Epilogue:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Grotesque","Variable","Modern"],license:"ofl",year:2020,popular:73},
  {id:"hanken-grotesk",name:"Hanken Grotesk",author:"Hanken Design Co.",cat:"sans-serif",gfamily:"Hanken+Grotesk:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Grotesque","Clean","Variable"],license:"ofl",year:2022,popular:71},
  // serif
  {id:"dm-serif-display",name:"DM Serif Display",author:"Colophon Foundry",cat:"serif",gfamily:"DM+Serif+Display:ital@0;1",weight:"400",tags:["Editorial","High-Contrast","Display"],license:"ofl",year:2019,popular:80},
  {id:"young-serif",name:"Young Serif",author:"Bastien Sozoo",cat:"serif",gfamily:"Young+Serif",weight:"400",tags:["Humanist","Chunky","Display"],license:"ofl",year:2023,popular:70},
  {id:"instrument-serif",name:"Instrument Serif",author:"Rodrigo Fuenzalida",cat:"serif",gfamily:"Instrument+Serif:ital@0;1",weight:"400",tags:["Elegant","Editorial","Italic"],license:"ofl",year:2023,popular:76},
  {id:"cardo",name:"Cardo",author:"David J. Perry",cat:"serif",gfamily:"Cardo:ital,wght@0,400;0,700;1,400",weight:"400",tags:["Academic","Unicode","Classic"],license:"ofl",year:2009,popular:73},
  {id:"neuton",name:"Neuton",author:"Brian Zick",cat:"serif",gfamily:"Neuton:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Classic","Reading","Literary"],license:"ofl",year:2011,popular:68},
  {id:"trirong",name:"Trirong",author:"Cadson Demak",cat:"serif",gfamily:"Trirong:ital,wght@0,300;0,400;0,700;1,400",weight:"400",tags:["Thai","Multilingual","Elegant"],license:"ofl",year:2016,popular:65},
  {id:"zilla-slab-highlight",name:"Zilla Slab Highlight",author:"Typotheque",cat:"serif",gfamily:"Zilla+Slab+Highlight:wght@400;700",weight:"700",tags:["Inline","Display","Mozilla"],license:"ofl",year:2017,popular:64},
  // display
  {id:"bricolage-grotesque",name:"Bricolage Grotesque",author:"Mathieu Triay",cat:"display",gfamily:"Bricolage+Grotesque:wght@300;400;500;600;700;800",weight:"700",tags:["Experimental","Variable","Modern"],license:"ofl",year:2023,popular:78},
  {id:"bungee",name:"Bungee",author:"David Jonathan Ross",cat:"display",gfamily:"Bungee",weight:"400",tags:["Signage","Bold","Retro"],license:"ofl",year:2015,popular:76},
  {id:"bowlby-one",name:"Bowlby One",author:"Cypress Type Foundry",cat:"display",gfamily:"Bowlby+One",weight:"400",tags:["Bold","Rounded","Retro"],license:"ofl",year:2012,popular:68},
  {id:"lilita-one",name:"Lilita One",author:"Fontourist",cat:"display",gfamily:"Lilita+One",weight:"400",tags:["Bold","Rounded","Display"],license:"ofl",year:2011,popular:73},
  {id:"iceland",name:"Iceland",author:"Beto Garza",cat:"display",gfamily:"Iceland",weight:"400",tags:["Sci-Fi","Futuristic","Tech"],license:"ofl",year:2012,popular:67},
  {id:"viga",name:"Viga",author:"Fontstage",cat:"display",gfamily:"Viga",weight:"400",tags:["Rounded","Bold","Heading"],license:"ofl",year:2012,popular:70},
  {id:"dm-serif-text",name:"DM Serif Text",author:"Colophon Foundry",cat:"display",gfamily:"DM+Serif+Text:ital@0;1",weight:"400",tags:["Editorial","High-Contrast","Reading"],license:"ofl",year:2019,popular:74},
  // handwriting
  {id:"marck-script",name:"Marck Script",author:"Jovanny Lemonad",cat:"handwriting",gfamily:"Marck+Script",weight:"400",tags:["Script","Casual","Cyrillic"],license:"ofl",year:2011,popular:72},
  {id:"mr-dafoe",name:"Mr Dafoe",author:"Sudtipos",cat:"handwriting",gfamily:"Mr+Dafoe",weight:"400",tags:["Formal","Calligraphy","Thin"],license:"apache",year:2013,popular:70},
  {id:"carattere",name:"Carattere",author:"Typefonts",cat:"handwriting",gfamily:"Carattere",weight:"400",tags:["Italic","Script","Elegant"],license:"ofl",year:2022,popular:65},
  {id:"birthstone",name:"Birthstone",author:"VTCo",cat:"handwriting",gfamily:"Birthstone",weight:"400",tags:["Calligraphy","Wedding","Formal"],license:"ofl",year:2021,popular:68},
  {id:"style-script",name:"Style Script",author:"Robert Leuschke",cat:"handwriting",gfamily:"Style+Script",weight:"400",tags:["Script","Formal","Elegant"],license:"ofl",year:2021,popular:67},
  {id:"imperial-script",name:"Imperial Script",author:"Robert Leuschke",cat:"handwriting",gfamily:"Imperial+Script",weight:"400",tags:["Calligraphy","Formal","Thin"],license:"ofl",year:2021,popular:64},
  {id:"waterfall",name:"Waterfall",author:"Robert Leuschke",cat:"handwriting",gfamily:"Waterfall",weight:"400",tags:["Script","Flowing","Elegant"],license:"ofl",year:2021,popular:66},
  {id:"mea-culpa",name:"Mea Culpa",author:"Robert Leuschke",cat:"handwriting",gfamily:"Mea+Culpa",weight:"400",tags:["Script","Italic","Formal"],license:"ofl",year:2022,popular:62},
  // monospace
  {id:"geist-mono",name:"Geist Mono",author:"Vercel",cat:"monospace",gfamily:"Geist+Mono:wght@300;400;500;700",weight:"400",tags:["Developer","Variable","Modern"],license:"ofl",year:2023,popular:85},
  {id:"martian-mono",name:"Martian Mono",author:"Roman Shamin",cat:"monospace",gfamily:"Martian+Mono:wght@300;400;500;700",weight:"400",tags:["Terminal","Condensed","Developer"],license:"ofl",year:2022,popular:73},
  {id:"fragment-mono",name:"Fragment Mono",author:"Haverford College",cat:"monospace",gfamily:"Fragment+Mono:ital@0;1",weight:"400",tags:["Monospace","Minimal","Code"],license:"ofl",year:2022,popular:70},
  {id:"commit-mono",name:"Commit Mono",author:"Eigil Nikolajsen",cat:"monospace",gfamily:"Commit+Mono",weight:"400",tags:["Code","Minimal","Neutral"],license:"ofl",year:2023,popular:76},
  {id:"sono",name:"Sono",author:"Tyler Finck",cat:"monospace",gfamily:"Sono:wght@300;400;500;700",weight:"400",tags:["Monospace","Variable","Rounded"],license:"ofl",year:2022,popular:69},
  // other
  {id:"boogaloo",name:"Boogaloo",author:"Latinotype",cat:"other",gfamily:"Boogaloo",weight:"400",tags:["Retro","Casual","Fun"],license:"ofl",year:2013,popular:75},
  {id:"pirata-one",name:"Pirata One",author:"Omnibus-Type",cat:"other",gfamily:"Pirata+One",weight:"400",tags:["Pirate","Gothic","Display"],license:"ofl",year:2015,popular:69},
  {id:"trade-winds",name:"Trade Winds",author:"Tart Workshop",cat:"other",gfamily:"Trade+Winds",weight:"400",tags:["Nautical","Retro","Display"],license:"apache",year:2011,popular:66},
  {id:"plaster",name:"Plaster",author:"Sorkin Type",cat:"other",gfamily:"Plaster",weight:"400",tags:["Hollow","Decorative","Display"],license:"apache",year:2011,popular:60},
  {id:"emblema-one",name:"Emblema One",author:"Impallari Type",cat:"other",gfamily:"Emblema+One",weight:"400",tags:["Decorative","Display","Ornate"],license:"ofl",year:2012,popular:62},
  {id:"fleur-de-leah",name:"Fleur De Leah",author:"Robert Leuschke",cat:"other",gfamily:"Fleur+De+Leah",weight:"400",tags:["Decorative","Calligraphy","Flowing"],license:"ofl",year:2021,popular:64},
  {id:"paprika",name:"Paprika",author:"Fontstage",cat:"other",gfamily:"Paprika",weight:"400",tags:["Decorative","Retro","Display"],license:"ofl",year:2012,popular:63},
  {id:"underdog",name:"Underdog",author:"TypeFaith Fonts",cat:"other",gfamily:"Underdog",weight:"400",tags:["Cyrillic","Casual","Display"],license:"ofl",year:2012,popular:61},
  {id:"metal-mania",name:"Metal Mania",author:"Astigmatic",cat:"other",gfamily:"Metal+Mania",weight:"400",tags:["Metal","Rock","Decorative"],license:"apache",year:2011,popular:62},
  {id:"ribeye",name:"Ribeye",author:"Astigmatic",cat:"other",gfamily:"Ribeye",weight:"400",tags:["Retro","Bold","Display"],license:"apache",year:2012,popular:64},
  {id:"smokum",name:"Smokum",author:"Astigmatic",cat:"other",gfamily:"Smokum",weight:"400",tags:["Western","Retro","Display"],license:"apache",year:2011,popular:58},
  {id:"flavors",name:"Flavors",author:"Astigmatic",cat:"other",gfamily:"Flavors",weight:"400",tags:["Decorative","Fun","Display"],license:"apache",year:2012,popular:60},
  {id:"hanalei-fill",name:"Hanalei Fill",author:"Sorkin Type",cat:"other",gfamily:"Hanalei+Fill",weight:"400",tags:["Tropical","Decorative","Retro"],license:"apache",year:2014,popular:63},
  {id:"vt323",name:"VT323",author:"Peter Hull",cat:"monospace",gfamily:"VT323",weight:"400",tags:["Pixel","Retro","Terminal"],license:"ofl",year:2014,popular:77},
  {id:"silkscreen",name:"Silkscreen",author:"Jason Kottke",cat:"monospace",gfamily:"Silkscreen:wght@400;700",weight:"400",tags:["Pixel","Bitmap","Retro"],license:"ofl",year:2021,popular:72},
];